export interface WordEntry {
  word: string;
  category: string;
}

export const WORD_BANK: WordEntry[] = [
  { word: "Doraemon", category: "Doraemon & Anime" },
  { word: "Nobita", category: "Doraemon & Anime" },
  { word: "Shizuka", category: "Doraemon & Anime" },
  { word: "Gian", category: "Doraemon & Anime" },
  { word: "Suneo", category: "Doraemon & Anime" },
  { word: "Dorami", category: "Doraemon & Anime" },
  { word: "AnywhereDoor", category: "Doraemon & Anime" },
  { word: "BambooCopter", category: "Doraemon & Anime" },
  { word: "TimeMachine", category: "Doraemon & Anime" },
  { word: "Pikachu", category: "Doraemon & Anime" },
  { word: "Naruto", category: "Doraemon & Anime" },
  { word: "Goku", category: "Doraemon & Anime" },
  { word: "Luffy", category: "Doraemon & Anime" },
  { word: "Charizard", category: "Doraemon & Anime" },
  { word: "Ash", category: "Doraemon & Anime" },
  { word: "Kakashi", category: "Doraemon & Anime" },
  { word: "Shinchan", category: "Shinchan & Cartoons" },
  { word: "Shiro", category: "Shinchan & Cartoons" },
  { word: "Himawari", category: "Shinchan & Cartoons" },
  { word: "ActionKamen", category: "Shinchan & Cartoons" },
  { word: "Misae", category: "Shinchan & Cartoons" },
  { word: "Hiroshi", category: "Shinchan & Cartoons" },
  { word: "Tom", category: "Shinchan & Cartoons" },
  { word: "Jerry", category: "Shinchan & Cartoons" },
  { word: "Mickey", category: "Shinchan & Cartoons" },
  { word: "Donald", category: "Shinchan & Cartoons" },
  { word: "Popeye", category: "Shinchan & Cartoons" },
  { word: "Scooby", category: "Shinchan & Cartoons" },
  { word: "Oggy", category: "Shinchan & Cartoons" },
  { word: "ChhotaBheem", category: "Shinchan & Cartoons" },
  { word: "MotuPatlu", category: "Shinchan & Cartoons" },
  { word: "SpongeBob", category: "Shinchan & Cartoons" },
  { word: "Patrick", category: "Shinchan & Cartoons" },
  { word: "BenTen", category: "Shinchan & Cartoons" },
  { word: "Dora", category: "Shinchan & Cartoons" },
  { word: "Cinderella", category: "Fairy Tales & Toys" },
  { word: "SnowWhite", category: "Fairy Tales & Toys" },
  { word: "Rapunzel", category: "Fairy Tales & Toys" },
  { word: "Pinocchio", category: "Fairy Tales & Toys" },
  { word: "PeterPan", category: "Fairy Tales & Toys" },
  { word: "RedRidingHood", category: "Fairy Tales & Toys" },
  { word: "Unicorn", category: "Fairy Tales & Toys" },
  { word: "Mermaid", category: "Fairy Tales & Toys" },
  { word: "TeddyBear", category: "Fairy Tales & Toys" },
  { word: "MagicWand", category: "Fairy Tales & Toys" },
  { word: "Dollhouse", category: "Fairy Tales & Toys" },
  { word: "ToyTrain", category: "Fairy Tales & Toys" },
  { word: "Crayons", category: "Fairy Tales & Toys" },
  { word: "PlayDough", category: "Fairy Tales & Toys" },
  { word: "Kite", category: "Fairy Tales & Toys" },
  { word: "Slide", category: "Fairy Tales & Toys" },
  { word: "Seesaw", category: "Fairy Tales & Toys" },
  { word: "Swing", category: "Fairy Tales & Toys" },
  { word: "Ironman", category: "Marvel & Superheroes" },
  { word: "Spiderman", category: "Marvel & Superheroes" },
  { word: "Thor", category: "Marvel & Superheroes" },
  { word: "Hulk", category: "Marvel & Superheroes" },
  { word: "CaptainAmerica", category: "Marvel & Superheroes" },
  { word: "Thanos", category: "Marvel & Superheroes" },
  { word: "Wolverine", category: "Marvel & Superheroes" },
  { word: "Deadpool", category: "Marvel & Superheroes" },
  { word: "Batman", category: "Marvel & Superheroes" },
  { word: "Superman", category: "Marvel & Superheroes" },
  { word: "Joker", category: "Marvel & Superheroes" },
  { word: "Avengers", category: "Marvel & Superheroes" },
  { word: "Groot", category: "Marvel & Superheroes" },
  { word: "Loki", category: "Marvel & Superheroes" },
  { word: "Hawkeye", category: "Marvel & Superheroes" },
  { word: "Flash", category: "Marvel & Superheroes" },
  { word: "BlackPanther", category: "Marvel & Superheroes" },
  { word: "Aquaman", category: "Marvel & Superheroes" },
  { word: "WonderWoman", category: "Marvel & Superheroes" },
  { word: "DoctorStrange", category: "Marvel & Superheroes" },
  { word: "HarryPotter", category: "Movies & Cinema" },
  { word: "Voldemort", category: "Movies & Cinema" },
  { word: "Avatar", category: "Movies & Cinema" },
  { word: "Titanic", category: "Movies & Cinema" },
  { word: "Barbie", category: "Movies & Cinema" },
  { word: "Shrek", category: "Movies & Cinema" },
  { word: "Simba", category: "Movies & Cinema" },
  { word: "Tarzan", category: "Movies & Cinema" },
  { word: "Aladdin", category: "Movies & Cinema" },
  { word: "JackSparrow", category: "Movies & Cinema" },
  { word: "Terminator", category: "Movies & Cinema" },
  { word: "StarWars", category: "Movies & Cinema" },
  { word: "Matrix", category: "Movies & Cinema" },
  { word: "JurassicPark", category: "Movies & Cinema" },
  { word: "Frozen", category: "Movies & Cinema" },
  { word: "Elsa", category: "Movies & Cinema" },
  { word: "Minions", category: "Movies & Cinema" },
  { word: "Inception", category: "Movies & Cinema" },
  { word: "Godzilla", category: "Movies & Cinema" },
  { word: "KingKong", category: "Movies & Cinema" },
  { word: "Mario", category: "Games & Gaming" },
  { word: "Luigi", category: "Games & Gaming" },
  { word: "Sonic", category: "Games & Gaming" },
  { word: "Minecraft", category: "Games & Gaming" },
  { word: "Roblox", category: "Games & Gaming" },
  { word: "Pokemon", category: "Games & Gaming" },
  { word: "Pubg", category: "Games & Gaming" },
  { word: "FreeFire", category: "Games & Gaming" },
  { word: "Pacman", category: "Games & Gaming" },
  { word: "AmongUs", category: "Games & Gaming" },
  { word: "Fortnite", category: "Games & Gaming" },
  { word: "GTA", category: "Games & Gaming" },
  { word: "SubwaySurfers", category: "Games & Gaming" },
  { word: "CandyCrush", category: "Games & Gaming" },
  { word: "AngryBirds", category: "Games & Gaming" },
  { word: "TempleRun", category: "Games & Gaming" },
  { word: "Instagram", category: "Social Media & Trends" },
  { word: "YouTube", category: "Social Media & Trends" },
  { word: "TikTok", category: "Social Media & Trends" },
  { word: "Netflix", category: "Social Media & Trends" },
  { word: "Spotify", category: "Social Media & Trends" },
  { word: "Meme", category: "Social Media & Trends" },
  { word: "Selfie", category: "Social Media & Trends" },
  { word: "Podcast", category: "Social Media & Trends" },
  { word: "Vlogger", category: "Social Media & Trends" },
  { word: "Emoji", category: "Social Media & Trends" },
  { word: "Influencer", category: "Social Media & Trends" },
  { word: "WiFi", category: "Social Media & Trends" },
  { word: "Snapchat", category: "Social Media & Trends" },
  { word: "Gamer", category: "Social Media & Trends" },
  { word: "Hashtag", category: "Social Media & Trends" },
  { word: "Lunchbox", category: "School & Campus" },
  { word: "Homework", category: "School & Campus" },
  { word: "Backpack", category: "School & Campus" },
  { word: "Locker", category: "School & Campus" },
  { word: "Classroom", category: "School & Campus" },
  { word: "Principal", category: "School & Campus" },
  { word: "Canteen", category: "School & Campus" },
  { word: "Examination", category: "School & Campus" },
  { word: "Uniform", category: "School & Campus" },
  { word: "Blackboard", category: "School & Campus" },
  { word: "Notebook", category: "School & Campus" },
  { word: "Recess", category: "School & Campus" },
  { word: "Library", category: "School & Campus" },
  { word: "Teacher", category: "School & Campus" },
  { word: "Nike", category: "Fashion & Style" },
  { word: "Adidas", category: "Fashion & Style" },
  { word: "Sneakers", category: "Fashion & Style" },
  { word: "Hoodie", category: "Fashion & Style" },
  { word: "Sunglasses", category: "Fashion & Style" },
  { word: "Watch", category: "Fashion & Style" },
  { word: "Perfume", category: "Fashion & Style" },
  { word: "Jacket", category: "Fashion & Style" },
  { word: "Jeans", category: "Fashion & Style" },
  { word: "Handbag", category: "Fashion & Style" },
  { word: "Lipstick", category: "Fashion & Style" },
  { word: "Cap", category: "Fashion & Style" },
  { word: "Coffee", category: "Work & Office Life" },
  { word: "Salary", category: "Work & Office Life" },
  { word: "Promotion", category: "Work & Office Life" },
  { word: "Meeting", category: "Work & Office Life" },
  { word: "Boss", category: "Work & Office Life" },
  { word: "Interview", category: "Work & Office Life" },
  { word: "Deadline", category: "Work & Office Life" },
  { word: "Presentation", category: "Work & Office Life" },
  { word: "Weekend", category: "Work & Office Life" },
  { word: "Vacation", category: "Work & Office Life" },
  { word: "Overtime", category: "Work & Office Life" },
  { word: "Resume", category: "Work & Office Life" },
  { word: "Bonus", category: "Work & Office Life" },
  { word: "Microwave", category: "Home & Daily Life" },
  { word: "Refrigerator", category: "Home & Daily Life" },
  { word: "Sofa", category: "Home & Daily Life" },
  { word: "Balcony", category: "Home & Daily Life" },
  { word: "Garden", category: "Home & Daily Life" },
  { word: "Kitchen", category: "Home & Daily Life" },
  { word: "Blender", category: "Home & Daily Life" },
  { word: "Wardrobe", category: "Home & Daily Life" },
  { word: "WashingMachine", category: "Home & Daily Life" },
  { word: "DiningTable", category: "Home & Daily Life" },
  { word: "AlarmClock", category: "Home & Daily Life" },
  { word: "Pillow", category: "Home & Daily Life" },
  { word: "Blanket", category: "Home & Daily Life" },
  { word: "Pizza", category: "Food & Snacks" },
  { word: "Burger", category: "Food & Snacks" },
  { word: "Chocolate", category: "Food & Snacks" },
  { word: "IceCream", category: "Food & Snacks" },
  { word: "Popcorn", category: "Food & Snacks" },
  { word: "FrenchFries", category: "Food & Snacks" },
  { word: "Maggi", category: "Food & Snacks" },
  { word: "Samosa", category: "Food & Snacks" },
  { word: "Biryani", category: "Food & Snacks" },
  { word: "Donut", category: "Food & Snacks" },
  { word: "Pancake", category: "Food & Snacks" },
  { word: "Sandwich", category: "Food & Snacks" },
  { word: "Cookie", category: "Food & Snacks" },
  { word: "Mango", category: "Food & Snacks" },
  { word: "Noodles", category: "Food & Snacks" },
  { word: "Cake", category: "Food & Snacks" },
  { word: "CottonCandy", category: "Food & Snacks" },
  { word: "Waffle", category: "Food & Snacks" },
  { word: "Taco", category: "Food & Snacks" },
  { word: "Nachos", category: "Food & Snacks" },
  { word: "Momos", category: "Food & Snacks" },
  { word: "Dosa", category: "Food & Snacks" },
  { word: "PaniPuri", category: "Food & Snacks" },
  { word: "Strawberry", category: "Food & Snacks" },
  { word: "Watermelon", category: "Food & Snacks" },
  { word: "Dog", category: "Popular Animals" },
  { word: "Cat", category: "Popular Animals" },
  { word: "Puppy", category: "Popular Animals" },
  { word: "Kitten", category: "Popular Animals" },
  { word: "Lion", category: "Popular Animals" },
  { word: "Tiger", category: "Popular Animals" },
  { word: "Monkey", category: "Popular Animals" },
  { word: "Panda", category: "Popular Animals" },
  { word: "Elephant", category: "Popular Animals" },
  { word: "Rabbit", category: "Popular Animals" },
  { word: "Dolphin", category: "Popular Animals" },
  { word: "Penguin", category: "Popular Animals" },
  { word: "Horse", category: "Popular Animals" },
  { word: "Giraffe", category: "Popular Animals" },
  { word: "Koala", category: "Popular Animals" },
  { word: "Bear", category: "Popular Animals" },
  { word: "Kangaroo", category: "Popular Animals" },
  { word: "Parrot", category: "Popular Animals" },
  { word: "Zebra", category: "Popular Animals" },
  { word: "Duck", category: "Popular Animals" },
  { word: "Butterfly", category: "Popular Animals" },
  { word: "Deer", category: "Popular Animals" },
  { word: "Mobile", category: "Cool Gadgets" },
  { word: "Laptop", category: "Cool Gadgets" },
  { word: "Headphones", category: "Cool Gadgets" },
  { word: "Bicycle", category: "Cool Gadgets" },
  { word: "Smartwatch", category: "Cool Gadgets" },
  { word: "Camera", category: "Cool Gadgets" },
  { word: "Drone", category: "Cool Gadgets" },
  { word: "Television", category: "Cool Gadgets" },
  { word: "Skateboard", category: "Cool Gadgets" },
  { word: "GamingConsole", category: "Cool Gadgets" },
  { word: "Robot", category: "Cool Gadgets" },
  { word: "Hoverboard", category: "Cool Gadgets" },
  { word: "Tablet", category: "Cool Gadgets" },
  { word: "Microphone", category: "Cool Gadgets" },
  { word: "Telescope", category: "Cool Gadgets" },
  { word: "Supercar", category: "Vehicles & Transport" },
  { word: "Motorcycle", category: "Vehicles & Transport" },
  { word: "Helicopter", category: "Vehicles & Transport" },
  { word: "Yacht", category: "Vehicles & Transport" },
  { word: "Metro", category: "Vehicles & Transport" },
  { word: "BulletTrain", category: "Vehicles & Transport" },
  { word: "Scooter", category: "Vehicles & Transport" },
  { word: "Ambulance", category: "Vehicles & Transport" },
  { word: "Taxi", category: "Vehicles & Transport" },
  { word: "Airplane", category: "Vehicles & Transport" },
  { word: "Submarine", category: "Vehicles & Transport" },
  { word: "Jeep", category: "Vehicles & Transport" },
  { word: "Cricket", category: "Sports & Games" },
  { word: "Football", category: "Sports & Games" },
  { word: "Badminton", category: "Sports & Games" },
  { word: "Basketball", category: "Sports & Games" },
  { word: "Tennis", category: "Sports & Games" },
  { word: "Chess", category: "Sports & Games" },
  { word: "Carrom", category: "Sports & Games" },
  { word: "Ludo", category: "Sports & Games" },
  { word: "Bowling", category: "Sports & Games" },
  { word: "Boxing", category: "Sports & Games" },
  { word: "Swimming", category: "Sports & Games" },
  { word: "Volleyball", category: "Sports & Games" },
  { word: "Cycling", category: "Sports & Games" },
  { word: "Skating", category: "Sports & Games" },
  { word: "Passport", category: "Travel & Adventures" },
  { word: "Suitcase", category: "Travel & Adventures" },
  { word: "Resort", category: "Travel & Adventures" },
  { word: "Campfire", category: "Travel & Adventures" },
  { word: "Souvenir", category: "Travel & Adventures" },
  { word: "Safari", category: "Travel & Adventures" },
  { word: "Tent", category: "Travel & Adventures" },
  { word: "RoadTrip", category: "Travel & Adventures" },
  { word: "WaterPark", category: "Fun Places" },
  { word: "CinemaHall", category: "Fun Places" },
  { word: "ShoppingMall", category: "Fun Places" },
  { word: "Beach", category: "Fun Places" },
  { word: "Zoo", category: "Fun Places" },
  { word: "Circus", category: "Fun Places" },
  { word: "AmusementPark", category: "Fun Places" },
  { word: "Airport", category: "Fun Places" },
  { word: "Castle", category: "Fun Places" },
  { word: "Island", category: "Fun Places" },
  { word: "Treehouse", category: "Fun Places" },
  { word: "Stadium", category: "Fun Places" },
  { word: "Vegeta", category: "Anime & Manga" },
  { word: "Sasuke", category: "Anime & Manga" },
  { word: "Sakura", category: "Anime & Manga" },
  { word: "Itachi", category: "Anime & Manga" },
  { word: "Zoro", category: "Anime & Manga" },
  { word: "Sanji", category: "Anime & Manga" },
  { word: "Nami", category: "Anime & Manga" },
  { word: "Chopper", category: "Anime & Manga" },
  { word: "Todoroki", category: "Anime & Manga" },
  { word: "Deku", category: "Anime & Manga" },
  { word: "Bakugo", category: "Anime & Manga" },
  { word: "AllMight", category: "Anime & Manga" },
  { word: "Gojo", category: "Anime & Manga" },
  { word: "Sukuna", category: "Anime & Manga" },
  { word: "Tanjiro", category: "Anime & Manga" },
  { word: "Nezuko", category: "Anime & Manga" },
  { word: "Zenitsu", category: "Anime & Manga" },
  { word: "Inosuke", category: "Anime & Manga" },
  { word: "Levi", category: "Anime & Manga" },
  { word: "Eren", category: "Anime & Manga" },
  { word: "Mikasa", category: "Anime & Manga" },
  { word: "Armin", category: "Anime & Manga" },
  { word: "LightYagami", category: "Anime & Manga" },
  { word: "Ryuk", category: "Anime & Manga" },
  { word: "Lelouch", category: "Anime & Manga" },
  { word: "SailorMoon", category: "Anime & Manga" },
  { word: "Shinji", category: "Anime & Manga" },
  { word: "Asuka", category: "Anime & Manga" },
  { word: "Kaneki", category: "Anime & Manga" },
  { word: "Saitama", category: "Anime & Manga" },
  { word: "Genos", category: "Anime & Manga" },
  { word: "Mob", category: "Anime & Manga" },
  { word: "Killua", category: "Anime & Manga" },
  { word: "Gon", category: "Anime & Manga" },
  { word: "Kurapika", category: "Anime & Manga" },
  { word: "Hisoka", category: "Anime & Manga" },
  { word: "Gengar", category: "Anime & Manga" },
  { word: "Mewtwo", category: "Anime & Manga" },
  { word: "Bulbasaur", category: "Anime & Manga" },
  { word: "Squirtle", category: "Anime & Manga" },
  { word: "Snorlax", category: "Anime & Manga" },
  { word: "Eevee", category: "Anime & Manga" },
  { word: "Lucario", category: "Anime & Manga" },
  { word: "Greninja", category: "Anime & Manga" },
  { word: "Digimon", category: "Anime & Manga" },
  { word: "Agumon", category: "Anime & Manga" },
  { word: "Yugioh", category: "Anime & Manga" },
  { word: "Exodia", category: "Anime & Manga" },
  { word: "Kamehameha", category: "Anime & Manga" },
  { word: "Rasengan", category: "Anime & Manga" },
  { word: "Sharinggan", category: "Anime & Manga" },
  { word: "Kunai", category: "Anime & Manga" },
  { word: "Shuriken", category: "Anime & Manga" },
  { word: "Katana", category: "Anime & Manga" },
  { word: "Bento", category: "Anime & Manga" },
  { word: "Onigiri", category: "Anime & Manga" },
  { word: "Ramen", category: "Anime & Manga" },
  { word: "Wasabi", category: "Anime & Manga" },
  { word: "Manga", category: "Anime & Manga" },
  { word: "Otaku", category: "Anime & Manga" },
  { word: "Sensei", category: "Anime & Manga" },
  { word: "Dojo", category: "Anime & Manga" },
  { word: "Kimono", category: "Anime & Manga" },
  { word: "Squidward", category: "Cartoons & Animation" },
  { word: "MrKrabs", category: "Cartoons & Animation" },
  { word: "Plankton", category: "Cartoons & Animation" },
  { word: "SandyCheeks", category: "Cartoons & Animation" },
  { word: "Gary", category: "Cartoons & Animation" },
  { word: "Fiona", category: "Cartoons & Animation" },
  { word: "Donkey", category: "Cartoons & Animation" },
  { word: "PussInBoots", category: "Cartoons & Animation" },
  { word: "Woody", category: "Cartoons & Animation" },
  { word: "BuzzLightyear", category: "Cartoons & Animation" },
  { word: "Rex", category: "Cartoons & Animation" },
  { word: "Slinky", category: "Cartoons & Animation" },
  { word: "Forky", category: "Cartoons & Animation" },
  { word: "LightningMcQueen", category: "Cartoons & Animation" },
  { word: "Mater", category: "Cartoons & Animation" },
  { word: "Nemo", category: "Cartoons & Animation" },
  { word: "Dory", category: "Cartoons & Animation" },
  { word: "Marlin", category: "Cartoons & Animation" },
  { word: "Sulley", category: "Cartoons & Animation" },
  { word: "MikeWazowski", category: "Cartoons & Animation" },
  { word: "WallE", category: "Cartoons & Animation" },
  { word: "Eve", category: "Cartoons & Animation" },
  { word: "Ratatouille", category: "Cartoons & Animation" },
  { word: "Remi", category: "Cartoons & Animation" },
  { word: "Po", category: "Cartoons & Animation" },
  { word: "MasterShifu", category: "Cartoons & Animation" },
  { word: "TaiLung", category: "Cartoons & Animation" },
  { word: "Tigress", category: "Cartoons & Animation" },
  { word: "Toothless", category: "Cartoons & Animation" },
  { word: "Hiccup", category: "Cartoons & Animation" },
  { word: "Gru", category: "Cartoons & Animation" },
  { word: "Stuart", category: "Cartoons & Animation" },
  { word: "Bob", category: "Cartoons & Animation" },
  { word: "Kevin", category: "Cartoons & Animation" },
  { word: "BugsBunny", category: "Cartoons & Animation" },
  { word: "DaffyDuck", category: "Cartoons & Animation" },
  { word: "Tweety", category: "Cartoons & Animation" },
  { word: "Sylvester", category: "Cartoons & Animation" },
  { word: "RoadRunner", category: "Cartoons & Animation" },
  { word: "Coyote", category: "Cartoons & Animation" },
  { word: "TasmanianDevil", category: "Cartoons & Animation" },
  { word: "Garfield", category: "Cartoons & Animation" },
  { word: "Odie", category: "Cartoons & Animation" },
  { word: "Snoopy", category: "Cartoons & Animation" },
  { word: "CharlieBrown", category: "Cartoons & Animation" },
  { word: "Dexter", category: "Cartoons & Animation" },
  { word: "DeeDee", category: "Cartoons & Animation" },
  { word: "JohnnyBravo", category: "Cartoons & Animation" },
  { word: "PowerpuffGirls", category: "Cartoons & Animation" },
  { word: "Blossom", category: "Cartoons & Animation" },
  { word: "Bubbles", category: "Cartoons & Animation" },
  { word: "Buttercup", category: "Cartoons & Animation" },
  { word: "MojoJojo", category: "Cartoons & Animation" },
  { word: "Courage", category: "Cartoons & Animation" },
  { word: "EdEddnEddy", category: "Cartoons & Animation" },
  { word: "Phineas", category: "Cartoons & Animation" },
  { word: "Ferb", category: "Cartoons & Animation" },
  { word: "PerryPlatypus", category: "Cartoons & Animation" },
  { word: "Doofenshmirtz", category: "Cartoons & Animation" },
  { word: "GravityFalls", category: "Cartoons & Animation" },
  { word: "Dipper", category: "Cartoons & Animation" },
  { word: "Mabel", category: "Cartoons & Animation" },
  { word: "Genie", category: "Fairy Tales & Legends" },
  { word: "Jafar", category: "Fairy Tales & Legends" },
  { word: "Abu", category: "Fairy Tales & Legends" },
  { word: "Iago", category: "Fairy Tales & Legends" },
  { word: "Jasmine", category: "Fairy Tales & Legends" },
  { word: "Jane", category: "Fairy Tales & Legends" },
  { word: "Hercules", category: "Fairy Tales & Legends" },
  { word: "Pegasus", category: "Fairy Tales & Legends" },
  { word: "Zeus", category: "Fairy Tales & Legends" },
  { word: "Hades", category: "Fairy Tales & Legends" },
  { word: "Poseidon", category: "Fairy Tales & Legends" },
  { word: "Medusa", category: "Fairy Tales & Legends" },
  { word: "Odin", category: "Fairy Tales & Legends" },
  { word: "Anubis", category: "Fairy Tales & Legends" },
  { word: "Cleopatra", category: "Fairy Tales & Legends" },
  { word: "Sphinx", category: "Fairy Tales & Legends" },
  { word: "Centaur", category: "Fairy Tales & Legends" },
  { word: "Minotaur", category: "Fairy Tales & Legends" },
  { word: "Cyclops", category: "Fairy Tales & Legends" },
  { word: "Hydra", category: "Fairy Tales & Legends" },
  { word: "Chupacabra", category: "Fairy Tales & Legends" },
  { word: "Bigfoot", category: "Fairy Tales & Legends" },
  { word: "Yeti", category: "Fairy Tales & Legends" },
  { word: "LochNess", category: "Fairy Tales & Legends" },
  { word: "Leprechaun", category: "Fairy Tales & Legends" },
  { word: "Gargoyle", category: "Fairy Tales & Legends" },
  { word: "Banshee", category: "Fairy Tales & Legends" },
  { word: "Valkyrie", category: "Fairy Tales & Legends" },
  { word: "Excalibur", category: "Fairy Tales & Legends" },
  { word: "Camelot", category: "Fairy Tales & Legends" },
  { word: "KingArthur", category: "Fairy Tales & Legends" },
  { word: "Merlin", category: "Fairy Tales & Legends" },
  { word: "RobinHood", category: "Fairy Tales & Legends" },
  { word: "Sherwood", category: "Fairy Tales & Legends" },
  { word: "LittleJohn", category: "Fairy Tales & Legends" },
  { word: "Goldilocks", category: "Fairy Tales & Legends" },
  { word: "Rumpelstiltskin", category: "Fairy Tales & Legends" },
  { word: "HumptyDumpty", category: "Fairy Tales & Legends" },
  { word: "BoPeep", category: "Fairy Tales & Legends" },
  { word: "Hansel", category: "Fairy Tales & Legends" },
  { word: "Gretel", category: "Fairy Tales & Legends" },
  { word: "GingerbreadMan", category: "Fairy Tales & Legends" },
  { word: "ToothFairy", category: "Fairy Tales & Legends" },
  { word: "Sandman", category: "Fairy Tales & Legends" },
  { word: "Cupid", category: "Fairy Tales & Legends" },
  { word: "Magneto", category: "Superheroes & Villains" },
  { word: "ProfessorX", category: "Superheroes & Villains" },
  { word: "JeanGrey", category: "Superheroes & Villains" },
  { word: "Storm", category: "Superheroes & Villains" },
  { word: "Beast", category: "Superheroes & Villains" },
  { word: "Nightcrawler", category: "Superheroes & Villains" },
  { word: "Mystique", category: "Superheroes & Villains" },
  { word: "Gambit", category: "Superheroes & Villains" },
  { word: "Rogue", category: "Superheroes & Villains" },
  { word: "Colossus", category: "Superheroes & Villains" },
  { word: "Sabretooth", category: "Superheroes & Villains" },
  { word: "Venom", category: "Superheroes & Villains" },
  { word: "Carnage", category: "Superheroes & Villains" },
  { word: "GreenGoblin", category: "Superheroes & Villains" },
  { word: "DocOck", category: "Superheroes & Villains" },
  { word: "Electro", category: "Superheroes & Villains" },
  { word: "Mysterio", category: "Superheroes & Villains" },
  { word: "Daredevil", category: "Superheroes & Villains" },
  { word: "Punisher", category: "Superheroes & Villains" },
  { word: "Elektra", category: "Superheroes & Villains" },
  { word: "Kingpin", category: "Superheroes & Villains" },
  { word: "Bullseye", category: "Superheroes & Villains" },
  { word: "MoonKnight", category: "Superheroes & Villains" },
  { word: "GhostRider", category: "Superheroes & Villains" },
  { word: "Blade", category: "Superheroes & Villains" },
  { word: "Morbius", category: "Superheroes & Villains" },
  { word: "Batmobile", category: "Superheroes & Villains" },
  { word: "Batarang", category: "Superheroes & Villains" },
  { word: "Batcave", category: "Superheroes & Villains" },
  { word: "Robin", category: "Superheroes & Villains" },
  { word: "Nightwing", category: "Superheroes & Villains" },
  { word: "Batgirl", category: "Superheroes & Villains" },
  { word: "Catwoman", category: "Superheroes & Villains" },
  { word: "Riddler", category: "Superheroes & Villains" },
  { word: "TwoFace", category: "Superheroes & Villains" },
  { word: "Bane", category: "Superheroes & Villains" },
  { word: "Scarecrow", category: "Superheroes & Villains" },
  { word: "PoisonIvy", category: "Superheroes & Villains" },
  { word: "HarleyQuinn", category: "Superheroes & Villains" },
  { word: "Supergirl", category: "Superheroes & Villains" },
  { word: "LexLuthor", category: "Superheroes & Villains" },
  { word: "Brainiac", category: "Superheroes & Villains" },
  { word: "GeneralZod", category: "Superheroes & Villains" },
  { word: "Doomsday", category: "Superheroes & Villains" },
  { word: "Darkseid", category: "Superheroes & Villains" },
  { word: "Shazam", category: "Superheroes & Villains" },
  { word: "BlackAdam", category: "Superheroes & Villains" },
  { word: "Cyborg", category: "Superheroes & Villains" },
  { word: "Starfire", category: "Superheroes & Villains" },
  { word: "Raven", category: "Superheroes & Villains" },
  { word: "BeastBoy", category: "Superheroes & Villains" },
  { word: "JamesBond", category: "Movies & TV Shows" },
  { word: "Goldeneye", category: "Movies & TV Shows" },
  { word: "AstonMartin", category: "Movies & TV Shows" },
  { word: "EthanHunt", category: "Movies & TV Shows" },
  { word: "MissionImpossible", category: "Movies & TV Shows" },
  { word: "JohnWick", category: "Movies & TV Shows" },
  { word: "Neo", category: "Movies & TV Shows" },
  { word: "Morpheus", category: "Movies & TV Shows" },
  { word: "Trinity", category: "Movies & TV Shows" },
  { word: "AgentSmith", category: "Movies & TV Shows" },
  { word: "Yoda", category: "Movies & TV Shows" },
  { word: "DarthVader", category: "Movies & TV Shows" },
  { word: "LukeSkywalker", category: "Movies & TV Shows" },
  { word: "PrincessLeia", category: "Movies & TV Shows" },
  { word: "HanSolo", category: "Movies & TV Shows" },
  { word: "Chewbacca", category: "Movies & TV Shows" },
  { word: "RD", category: "Movies & TV Shows" },
  { word: "CPO", category: "Movies & TV Shows" },
  { word: "Stormtrooper", category: "Movies & TV Shows" },
  { word: "Lightsaber", category: "Movies & TV Shows" },
  { word: "MillenniumFalcon", category: "Movies & TV Shows" },
  { word: "DeathStar", category: "Movies & TV Shows" },
  { word: "IndianaJones", category: "Movies & TV Shows" },
  { word: "Jurassic", category: "Movies & TV Shows" },
  { word: "TRex", category: "Movies & TV Shows" },
  { word: "Velociraptor", category: "Movies & TV Shows" },
  { word: "Gollum", category: "Movies & TV Shows" },
  { word: "Frodo", category: "Movies & TV Shows" },
  { word: "Gandalf", category: "Movies & TV Shows" },
  { word: "Legolas", category: "Movies & TV Shows" },
  { word: "Aragorn", category: "Movies & TV Shows" },
  { word: "Sauron", category: "Movies & TV Shows" },
  { word: "Mordor", category: "Movies & TV Shows" },
  { word: "Hobbit", category: "Movies & TV Shows" },
  { word: "Dumbledore", category: "Movies & TV Shows" },
  { word: "Snape", category: "Movies & TV Shows" },
  { word: "Hagrid", category: "Movies & TV Shows" },
  { word: "Hermione", category: "Movies & TV Shows" },
  { word: "RonWeasley", category: "Movies & TV Shows" },
  { word: "Quidditch", category: "Movies & TV Shows" },
  { word: "Gryffindor", category: "Movies & TV Shows" },
  { word: "Hogwarts", category: "Movies & TV Shows" },
  { word: "Horcrux", category: "Movies & TV Shows" },
  { word: "Transformer", category: "Movies & TV Shows" },
  { word: "OptimusPrime", category: "Movies & TV Shows" },
  { word: "Bumblebee", category: "Movies & TV Shows" },
  { word: "Megatron", category: "Movies & TV Shows" },
  { word: "RoboCop", category: "Movies & TV Shows" },
  { word: "Bowser", category: "Video Games & Gaming" },
  { word: "Peach", category: "Video Games & Gaming" },
  { word: "Toad", category: "Video Games & Gaming" },
  { word: "Yoshi", category: "Video Games & Gaming" },
  { word: "Wario", category: "Video Games & Gaming" },
  { word: "Waluigi", category: "Video Games & Gaming" },
  { word: "DonkeyKong", category: "Video Games & Gaming" },
  { word: "DiddyKong", category: "Video Games & Gaming" },
  { word: "Tails", category: "Video Games & Gaming" },
  { word: "Knuckles", category: "Video Games & Gaming" },
  { word: "Shadow", category: "Video Games & Gaming" },
  { word: "DrEggman", category: "Video Games & Gaming" },
  { word: "Steve", category: "Video Games & Gaming" },
  { word: "Creeper", category: "Video Games & Gaming" },
  { word: "Enderman", category: "Video Games & Gaming" },
  { word: "EnderDragon", category: "Video Games & Gaming" },
  { word: "DiamondPickaxe", category: "Video Games & Gaming" },
  { word: "Netherite", category: "Video Games & Gaming" },
  { word: "Redstone", category: "Video Games & Gaming" },
  { word: "PortalGun", category: "Video Games & Gaming" },
  { word: "GLaDOS", category: "Video Games & Gaming" },
  { word: "MasterChief", category: "Video Games & Gaming" },
  { word: "Cortana", category: "Video Games & Gaming" },
  { word: "DoomSlayer", category: "Video Games & Gaming" },
  { word: "GordonFreeman", category: "Video Games & Gaming" },
  { word: "Crowbar", category: "Video Games & Gaming" },
  { word: "CloudStrife", category: "Video Games & Gaming" },
  { word: "Sephiroth", category: "Video Games & Gaming" },
  { word: "Link", category: "Video Games & Gaming" },
  { word: "Zelda", category: "Video Games & Gaming" },
  { word: "Ganon", category: "Video Games & Gaming" },
  { word: "MasterSword", category: "Video Games & Gaming" },
  { word: "Triforce", category: "Video Games & Gaming" },
  { word: "SolidSnake", category: "Video Games & Gaming" },
  { word: "ArthurMorgan", category: "Video Games & Gaming" },
  { word: "JohnMarston", category: "Video Games & Gaming" },
  { word: "Trevor", category: "Video Games & Gaming" },
  { word: "Franklin", category: "Video Games & Gaming" },
  { word: "Michael", category: "Video Games & Gaming" },
  { word: "CJ", category: "Video Games & Gaming" },
  { word: "BigSmoke", category: "Video Games & Gaming" },
  { word: "Geralt", category: "Video Games & Gaming" },
  { word: "Ciri", category: "Video Games & Gaming" },
  { word: "Yennefer", category: "Video Games & Gaming" },
  { word: "Ellie", category: "Video Games & Gaming" },
  { word: "Joel", category: "Video Games & Gaming" },
  { word: "Kratos", category: "Video Games & Gaming" },
  { word: "Atreus", category: "Video Games & Gaming" },
  { word: "LeviathanAxe", category: "Video Games & Gaming" },
  { word: "Headshot", category: "Video Games & Gaming" },
  { word: "Respawn", category: "Video Games & Gaming" },
  { word: "Noob", category: "Video Games & Gaming" },
  { word: "Speedrun", category: "Video Games & Gaming" },
  { word: "Aimbot", category: "Video Games & Gaming" },
  { word: "Hitbox", category: "Video Games & Gaming" },
  { word: "EasterEgg", category: "Video Games & Gaming" },
  { word: "Binge", category: "Internet & Trends" },
  { word: "Streamer", category: "Internet & Trends" },
  { word: "YouTuber", category: "Internet & Trends" },
  { word: "Tiktoker", category: "Internet & Trends" },
  { word: "Goat", category: "Internet & Trends" },
  { word: "Vibe", category: "Internet & Trends" },
  { word: "Rizz", category: "Internet & Trends" },
  { word: "Flex", category: "Internet & Trends" },
  { word: "Hype", category: "Internet & Trends" },
  { word: "Cringe", category: "Internet & Trends" },
  { word: "Sus", category: "Internet & Trends" },
  { word: "Drip", category: "Internet & Trends" },
  { word: "Bop", category: "Internet & Trends" },
  { word: "GlowUp", category: "Internet & Trends" },
  { word: "Boomer", category: "Internet & Trends" },
  { word: "Karen", category: "Internet & Trends" },
  { word: "Simp", category: "Internet & Trends" },
  { word: "Stan", category: "Internet & Trends" },
  { word: "Ghosting", category: "Internet & Trends" },
  { word: "Catfish", category: "Internet & Trends" },
  { word: "Spoiler", category: "Internet & Trends" },
  { word: "Troll", category: "Internet & Trends" },
  { word: "Clickbait", category: "Internet & Trends" },
  { word: "Algorithm", category: "Internet & Trends" },
  { word: "Trending", category: "Internet & Trends" },
  { word: "Viral", category: "Internet & Trends" },
  { word: "Follower", category: "Internet & Trends" },
  { word: "Subscriber", category: "Internet & Trends" },
  { word: "Notification", category: "Internet & Trends" },
  { word: "Unbox", category: "Internet & Trends" },
  { word: "Challenge", category: "Internet & Trends" },
  { word: "React", category: "Internet & Trends" },
  { word: "Tutorial", category: "Internet & Trends" },
  { word: "Review", category: "Internet & Trends" },
  { word: "Thumbnails", category: "Internet & Trends" },
  { word: "Collab", category: "Internet & Trends" },
  { word: "Sponsor", category: "Internet & Trends" },
  { word: "Giveaway", category: "Internet & Trends" },
  { word: "Livestream", category: "Internet & Trends" },
  { word: "Superchat", category: "Internet & Trends" },
  { word: "Discord", category: "Internet & Trends" },
  { word: "Twitch", category: "Internet & Trends" },
  { word: "Reddit", category: "Internet & Trends" },
  { word: "Upvote", category: "Internet & Trends" },
  { word: "Karma", category: "Internet & Trends" },
  { word: "Subreddit", category: "Internet & Trends" },
  { word: "Pinterest", category: "Internet & Trends" },
  { word: "WhatsApp", category: "Internet & Trends" },
  { word: "Telegram", category: "Internet & Trends" },
  { word: "Snap", category: "Internet & Trends" },
  { word: "Cheeseburger", category: "Food & Treats" },
  { word: "Hotdog", category: "Food & Treats" },
  { word: "CornDog", category: "Food & Treats" },
  { word: "Nuggets", category: "Food & Treats" },
  { word: "ChickenWings", category: "Food & Treats" },
  { word: "OnionRings", category: "Food & Treats" },
  { word: "MozzarellaSticks", category: "Food & Treats" },
  { word: "Quesadilla", category: "Food & Treats" },
  { word: "Enchilada", category: "Food & Treats" },
  { word: "Fajita", category: "Food & Treats" },
  { word: "Guacamole", category: "Food & Treats" },
  { word: "Salsa", category: "Food & Treats" },
  { word: "Tortilla", category: "Food & Treats" },
  { word: "Pita", category: "Food & Treats" },
  { word: "Hummus", category: "Food & Treats" },
  { word: "Falafel", category: "Food & Treats" },
  { word: "Shawarma", category: "Food & Treats" },
  { word: "Kebab", category: "Food & Treats" },
  { word: "Gyros", category: "Food & Treats" },
  { word: "Calzone", category: "Food & Treats" },
  { word: "Risotto", category: "Food & Treats" },
  { word: "Ravioli", category: "Food & Treats" },
  { word: "Gnocchi", category: "Food & Treats" },
  { word: "Bruschetta", category: "Food & Treats" },
  { word: "Tiramisu", category: "Food & Treats" },
  { word: "PannaCotta", category: "Food & Treats" },
  { word: "Gelato", category: "Food & Treats" },
  { word: "Cannoli", category: "Food & Treats" },
  { word: "Macarons", category: "Food & Treats" },
  { word: "Eclair", category: "Food & Treats" },
  { word: "Souffle", category: "Food & Treats" },
  { word: "Crepe", category: "Food & Treats" },
  { word: "Fondue", category: "Food & Treats" },
  { word: "Pretzel", category: "Food & Treats" },
  { word: "Bagel", category: "Food & Treats" },
  { word: "Croissant", category: "Food & Treats" },
  { word: "Muffin", category: "Food & Treats" },
  { word: "Scone", category: "Food & Treats" },
  { word: "Cupcake", category: "Food & Treats" },
  { word: "Brownie", category: "Food & Treats" },
  { word: "Fudge", category: "Food & Treats" },
  { word: "Toffee", category: "Food & Treats" },
  { word: "Lollipop", category: "Food & Treats" },
  { word: "Jellybean", category: "Food & Treats" },
  { word: "GummyBear", category: "Food & Treats" },
  { word: "Licorice", category: "Food & Treats" },
  { word: "Marshmallow", category: "Food & Treats" },
  { word: "Churros", category: "Food & Treats" },
  { word: "Sundae", category: "Food & Treats" },
  { word: "Milkshake", category: "Food & Treats" },
  { word: "Smoothie", category: "Food & Treats" },
  { word: "Slushie", category: "Food & Treats" },
  { word: "BubbleTea", category: "Food & Treats" },
  { word: "Lemonade", category: "Food & Treats" },
  { word: "ButterChicken", category: "Desi Street Food & Sweets" },
  { word: "PaneerTikka", category: "Desi Street Food & Sweets" },
  { word: "Naan", category: "Desi Street Food & Sweets" },
  { word: "Roti", category: "Desi Street Food & Sweets" },
  { word: "Paratha", category: "Desi Street Food & Sweets" },
  { word: "DalMakhani", category: "Desi Street Food & Sweets" },
  { word: "CholeBhature", category: "Desi Street Food & Sweets" },
  { word: "PavBhaji", category: "Desi Street Food & Sweets" },
  { word: "VadaPav", category: "Desi Street Food & Sweets" },
  { word: "BhelPuri", category: "Desi Street Food & Sweets" },
  { word: "SevPuri", category: "Desi Street Food & Sweets" },
  { word: "DahiPuri", category: "Desi Street Food & Sweets" },
  { word: "RajKachori", category: "Desi Street Food & Sweets" },
  { word: "AlooTikki", category: "Desi Street Food & Sweets" },
  { word: "GulabJamun", category: "Desi Street Food & Sweets" },
  { word: "Rasgulla", category: "Desi Street Food & Sweets" },
  { word: "Jalebi", category: "Desi Street Food & Sweets" },
  { word: "KajuKatli", category: "Desi Street Food & Sweets" },
  { word: "Laddu", category: "Desi Street Food & Sweets" },
  { word: "Barfi", category: "Desi Street Food & Sweets" },
  { word: "Rasmalai", category: "Desi Street Food & Sweets" },
  { word: "Halwa", category: "Desi Street Food & Sweets" },
  { word: "Kheer", category: "Desi Street Food & Sweets" },
  { word: "Lassi", category: "Desi Street Food & Sweets" },
  { word: "Chai", category: "Desi Street Food & Sweets" },
  { word: "MasalaChai", category: "Desi Street Food & Sweets" },
  { word: "Idli", category: "Desi Street Food & Sweets" },
  { word: "Vada", category: "Desi Street Food & Sweets" },
  { word: "Uttapam", category: "Desi Street Food & Sweets" },
  { word: "Upma", category: "Desi Street Food & Sweets" },
  { word: "Poha", category: "Desi Street Food & Sweets" },
  { word: "Dhokla", category: "Desi Street Food & Sweets" },
  { word: "Khandvi", category: "Desi Street Food & Sweets" },
  { word: "Thepla", category: "Desi Street Food & Sweets" },
  { word: "Papad", category: "Desi Street Food & Sweets" },
  { word: "Chutney", category: "Desi Street Food & Sweets" },
  { word: "Raita", category: "Desi Street Food & Sweets" },
  { word: "Pulao", category: "Desi Street Food & Sweets" },
  { word: "KathiRoll", category: "Desi Street Food & Sweets" },
  { word: "Pakora", category: "Desi Street Food & Sweets" },
  { word: "Espresso", category: "Drinks & Café" },
  { word: "Cappuccino", category: "Drinks & Café" },
  { word: "Latte", category: "Drinks & Café" },
  { word: "Mocha", category: "Drinks & Café" },
  { word: "Americano", category: "Drinks & Café" },
  { word: "Macchiato", category: "Drinks & Café" },
  { word: "ColdBrew", category: "Drinks & Café" },
  { word: "Frappuccino", category: "Drinks & Café" },
  { word: "GreenTea", category: "Drinks & Café" },
  { word: "BlackTea", category: "Drinks & Café" },
  { word: "ChaiLatte", category: "Drinks & Café" },
  { word: "HotChocolate", category: "Drinks & Café" },
  { word: "Mocktail", category: "Drinks & Café" },
  { word: "Cocktail", category: "Drinks & Café" },
  { word: "IcedTea", category: "Drinks & Café" },
  { word: "FruitPunch", category: "Drinks & Café" },
  { word: "GingerAle", category: "Drinks & Café" },
  { word: "Cider", category: "Drinks & Café" },
  { word: "CoconutWater", category: "Drinks & Café" },
  { word: "AppleJuice", category: "Drinks & Café" },
  { word: "OrangeJuice", category: "Drinks & Café" },
  { word: "MangoJuice", category: "Drinks & Café" },
  { word: "Sugarcane", category: "Drinks & Café" },
  { word: "Buttermilk", category: "Drinks & Café" },
  { word: "Mojito", category: "Drinks & Café" },
  { word: "PinaColada", category: "Drinks & Café" },
  { word: "Margarita", category: "Drinks & Café" },
  { word: "Sangria", category: "Drinks & Café" },
  { word: "EspressoTonic", category: "Drinks & Café" },
  { word: "Jaguar", category: "Wild & Exotic Animals" },
  { word: "Leopard", category: "Wild & Exotic Animals" },
  { word: "Cheetah", category: "Wild & Exotic Animals" },
  { word: "Cougar", category: "Wild & Exotic Animals" },
  { word: "Lynx", category: "Wild & Exotic Animals" },
  { word: "Bobcat", category: "Wild & Exotic Animals" },
  { word: "Grizzly", category: "Wild & Exotic Animals" },
  { word: "PolarBear", category: "Wild & Exotic Animals" },
  { word: "PandaBear", category: "Wild & Exotic Animals" },
  { word: "SunBear", category: "Wild & Exotic Animals" },
  { word: "Hyena", category: "Wild & Exotic Animals" },
  { word: "Jackal", category: "Wild & Exotic Animals" },
  { word: "WildDog", category: "Wild & Exotic Animals" },
  { word: "Dingo", category: "Wild & Exotic Animals" },
  { word: "Meerkat", category: "Wild & Exotic Animals" },
  { word: "Mongoose", category: "Wild & Exotic Animals" },
  { word: "Wombat", category: "Wild & Exotic Animals" },
  { word: "Badger", category: "Wild & Exotic Animals" },
  { word: "Skunk", category: "Wild & Exotic Animals" },
  { word: "Otter", category: "Wild & Exotic Animals" },
  { word: "Weasel", category: "Wild & Exotic Animals" },
  { word: "Ferret", category: "Wild & Exotic Animals" },
  { word: "Armadillo", category: "Wild & Exotic Animals" },
  { word: "Anteater", category: "Wild & Exotic Animals" },
  { word: "Pangolin", category: "Wild & Exotic Animals" },
  { word: "Porcupine", category: "Wild & Exotic Animals" },
  { word: "Hedgehog", category: "Wild & Exotic Animals" },
  { word: "Opossum", category: "Wild & Exotic Animals" },
  { word: "Chinchilla", category: "Wild & Exotic Animals" },
  { word: "Capybara", category: "Wild & Exotic Animals" },
  { word: "GuineaPig", category: "Wild & Exotic Animals" },
  { word: "Beaver", category: "Wild & Exotic Animals" },
  { word: "Muskrat", category: "Wild & Exotic Animals" },
  { word: "Chipmunk", category: "Wild & Exotic Animals" },
  { word: "PrairieDog", category: "Wild & Exotic Animals" },
  { word: "Baboon", category: "Wild & Exotic Animals" },
  { word: "Mandrill", category: "Wild & Exotic Animals" },
  { word: "Macaque", category: "Wild & Exotic Animals" },
  { word: "Gibbon", category: "Wild & Exotic Animals" },
  { word: "Orangutan", category: "Wild & Exotic Animals" },
  { word: "Gorilla", category: "Wild & Exotic Animals" },
  { word: "BaldEagle", category: "Sea Life, Birds & Reptiles" },
  { word: "GoldenEagle", category: "Sea Life, Birds & Reptiles" },
  { word: "Osprey", category: "Sea Life, Birds & Reptiles" },
  { word: "Falcon", category: "Sea Life, Birds & Reptiles" },
  { word: "Hawk", category: "Sea Life, Birds & Reptiles" },
  { word: "Vulture", category: "Sea Life, Birds & Reptiles" },
  { word: "BarnOwl", category: "Sea Life, Birds & Reptiles" },
  { word: "SnowyOwl", category: "Sea Life, Birds & Reptiles" },
  { word: "Flamingo", category: "Sea Life, Birds & Reptiles" },
  { word: "Pelican", category: "Sea Life, Birds & Reptiles" },
  { word: "Toucan", category: "Sea Life, Birds & Reptiles" },
  { word: "Macaw", category: "Sea Life, Birds & Reptiles" },
  { word: "Cockatoo", category: "Sea Life, Birds & Reptiles" },
  { word: "Hummingbird", category: "Sea Life, Birds & Reptiles" },
  { word: "Woodpecker", category: "Sea Life, Birds & Reptiles" },
  { word: "Kingfisher", category: "Sea Life, Birds & Reptiles" },
  { word: "BlueJay", category: "Sea Life, Birds & Reptiles" },
  { word: "Cardinal", category: "Sea Life, Birds & Reptiles" },
  { word: "Swallow", category: "Sea Life, Birds & Reptiles" },
  { word: "Albatross", category: "Sea Life, Birds & Reptiles" },
  { word: "GreatWhite", category: "Sea Life, Birds & Reptiles" },
  { word: "Hammerhead", category: "Sea Life, Birds & Reptiles" },
  { word: "TigerShark", category: "Sea Life, Birds & Reptiles" },
  { word: "WhaleShark", category: "Sea Life, Birds & Reptiles" },
  { word: "MantaRay", category: "Sea Life, Birds & Reptiles" },
  { word: "Stingray", category: "Sea Life, Birds & Reptiles" },
  { word: "ElectricEel", category: "Sea Life, Birds & Reptiles" },
  { word: "MorayEel", category: "Sea Life, Birds & Reptiles" },
  { word: "Barracuda", category: "Sea Life, Birds & Reptiles" },
  { word: "Piranha", category: "Sea Life, Birds & Reptiles" },
  { word: "Swordfish", category: "Sea Life, Birds & Reptiles" },
  { word: "Tuna", category: "Sea Life, Birds & Reptiles" },
  { word: "Salmon", category: "Sea Life, Birds & Reptiles" },
  { word: "Clownfish", category: "Sea Life, Birds & Reptiles" },
  { word: "Angelfish", category: "Sea Life, Birds & Reptiles" },
  { word: "Lionfish", category: "Sea Life, Birds & Reptiles" },
  { word: "Blowfish", category: "Sea Life, Birds & Reptiles" },
  { word: "Seahorse", category: "Sea Life, Birds & Reptiles" },
  { word: "Octopus", category: "Sea Life, Birds & Reptiles" },
  { word: "Squid", category: "Sea Life, Birds & Reptiles" },
  { word: "GiantSquid", category: "Sea Life, Birds & Reptiles" },
  { word: "Cuttlefish", category: "Sea Life, Birds & Reptiles" },
  { word: "Nautilus", category: "Sea Life, Birds & Reptiles" },
  { word: "Chameleon", category: "Sea Life, Birds & Reptiles" },
  { word: "Gecko", category: "Sea Life, Birds & Reptiles" },
  { word: "KomodoDragon", category: "Sea Life, Birds & Reptiles" },
  { word: "Anaconda", category: "Sea Life, Birds & Reptiles" },
  { word: "BoaConstrictor", category: "Sea Life, Birds & Reptiles" },
  { word: "Cobra", category: "Sea Life, Birds & Reptiles" },
  { word: "Viper", category: "Sea Life, Birds & Reptiles" },
  { word: "Rattlesnake", category: "Sea Life, Birds & Reptiles" },
  { word: "Alligator", category: "Sea Life, Birds & Reptiles" },
  { word: "Smartphone", category: "Tech & Gadgets" },
  { word: "SmartGlasses", category: "Tech & Gadgets" },
  { word: "VirtualReality", category: "Tech & Gadgets" },
  { word: "AugmentedReality", category: "Tech & Gadgets" },
  { word: "Quadcop", category: "Tech & Gadgets" },
  { word: "Gimbal", category: "Tech & Gadgets" },
  { word: "GoPro", category: "Tech & Gadgets" },
  { word: "Tripod", category: "Tech & Gadgets" },
  { word: "Webcam", category: "Tech & Gadgets" },
  { word: "StudioLights", category: "Tech & Gadgets" },
  { word: "Keychron", category: "Tech & Gadgets" },
  { word: "MechanicalKeyboard", category: "Tech & Gadgets" },
  { word: "GamingMouse", category: "Tech & Gadgets" },
  { word: "Mousepad", category: "Tech & Gadgets" },
  { word: "UltrawideMonitor", category: "Tech & Gadgets" },
  { word: "PowerBank", category: "Tech & Gadgets" },
  { word: "WirelessCharger", category: "Tech & Gadgets" },
  { word: "Earbuds", category: "Tech & Gadgets" },
  { word: "AirPods", category: "Tech & Gadgets" },
  { word: "Headset", category: "Tech & Gadgets" },
  { word: "Soundbar", category: "Tech & Gadgets" },
  { word: "Subwoofer", category: "Tech & Gadgets" },
  { word: "Projector", category: "Tech & Gadgets" },
  { word: "Kindle", category: "Tech & Gadgets" },
  { word: "EReader", category: "Tech & Gadgets" },
  { word: "Stylus", category: "Tech & Gadgets" },
  { word: "DrawingTablet", category: "Tech & Gadgets" },
  { word: "FlashDrive", category: "Tech & Gadgets" },
  { word: "HardDrive", category: "Tech & Gadgets" },
  { word: "SolidStateDrive", category: "Tech & Gadgets" },
  { word: "Router", category: "Tech & Gadgets" },
  { word: "Modem", category: "Tech & Gadgets" },
  { word: "Server", category: "Tech & Gadgets" },
  { word: "Motherboard", category: "Tech & Gadgets" },
  { word: "GraphicsCard", category: "Tech & Gadgets" },
  { word: "Processor", category: "Tech & Gadgets" },
  { word: "QuantumComputer", category: "Tech & Gadgets" },
  { word: "Nanobot", category: "Tech & Gadgets" },
  { word: "Exoskeleton", category: "Tech & Gadgets" },
  { word: "Ferrari", category: "Vehicles & Speed" },
  { word: "Lamborghini", category: "Vehicles & Speed" },
  { word: "Porsche", category: "Vehicles & Speed" },
  { word: "Bugatti", category: "Vehicles & Speed" },
  { word: "McLaren", category: "Vehicles & Speed" },
  { word: "Mustang", category: "Vehicles & Speed" },
  { word: "Camaro", category: "Vehicles & Speed" },
  { word: "Corvette", category: "Vehicles & Speed" },
  { word: "Tesla", category: "Vehicles & Speed" },
  { word: "Cybertruck", category: "Vehicles & Speed" },
  { word: "MonsterTruck", category: "Vehicles & Speed" },
  { word: "FormulaOne", category: "Vehicles & Speed" },
  { word: "GoKart", category: "Vehicles & Speed" },
  { word: "DirtBike", category: "Vehicles & Speed" },
  { word: "Harley", category: "Vehicles & Speed" },
  { word: "Ducati", category: "Vehicles & Speed" },
  { word: "Hayabusa", category: "Vehicles & Speed" },
  { word: "Vespa", category: "Vehicles & Speed" },
  { word: "Segway", category: "Vehicles & Speed" },
  { word: "Snowmobile", category: "Vehicles & Speed" },
  { word: "JetSki", category: "Vehicles & Speed" },
  { word: "Speedboat", category: "Vehicles & Speed" },
  { word: "Catamaran", category: "Vehicles & Speed" },
  { word: "Hovercraft", category: "Vehicles & Speed" },
  { word: "CargoShip", category: "Vehicles & Speed" },
  { word: "AircraftCarrier", category: "Vehicles & Speed" },
  { word: "StealthBomber", category: "Vehicles & Speed" },
  { word: "FighterJet", category: "Vehicles & Speed" },
  { word: "Concorde", category: "Vehicles & Speed" },
  { word: "Zeppelin", category: "Vehicles & Speed" },
  { word: "HotAirBalloon", category: "Vehicles & Speed" },
  { word: "Glider", category: "Vehicles & Speed" },
  { word: "SpaceShuttle", category: "Vehicles & Speed" },
  { word: "LunarRover", category: "Vehicles & Speed" },
  { word: "MarsRover", category: "Vehicles & Speed" },
  { word: "Monorail", category: "Vehicles & Speed" },
  { word: "CableCar", category: "Vehicles & Speed" },
  { word: "SteamEngine", category: "Vehicles & Speed" },
  { word: "Forklift", category: "Vehicles & Speed" },
  { word: "Bulldozer", category: "Vehicles & Speed" },
  { word: "Baseball", category: "Sports & Athletics" },
  { word: "Soccer", category: "Sports & Athletics" },
  { word: "Rugby", category: "Sports & Athletics" },
  { word: "TableTennis", category: "Sports & Athletics" },
  { word: "WaterPolo", category: "Sports & Athletics" },
  { word: "Handball", category: "Sports & Athletics" },
  { word: "Dodgeball", category: "Sports & Athletics" },
  { word: "Lacrosse", category: "Sports & Athletics" },
  { word: "Hockey", category: "Sports & Athletics" },
  { word: "IceHockey", category: "Sports & Athletics" },
  { word: "Curling", category: "Sports & Athletics" },
  { word: "FigureSkating", category: "Sports & Athletics" },
  { word: "SpeedSkating", category: "Sports & Athletics" },
  { word: "Snowboarding", category: "Sports & Athletics" },
  { word: "SkiJumping", category: "Sports & Athletics" },
  { word: "Bobsled", category: "Sports & Athletics" },
  { word: "Luge", category: "Sports & Athletics" },
  { word: "Skateboarding", category: "Sports & Athletics" },
  { word: "Surfing", category: "Sports & Athletics" },
  { word: "Windsurfing", category: "Sports & Athletics" },
  { word: "Kitesurfing", category: "Sports & Athletics" },
  { word: "Wakeboarding", category: "Sports & Athletics" },
  { word: "Bodyboarding", category: "Sports & Athletics" },
  { word: "ScubaDiving", category: "Sports & Athletics" },
  { word: "FreeDiving", category: "Sports & Athletics" },
  { word: "RockClimbing", category: "Sports & Athletics" },
  { word: "Bouldering", category: "Sports & Athletics" },
  { word: "Parkour", category: "Sports & Athletics" },
  { word: "Gymnastics", category: "Sports & Athletics" },
  { word: "Trampoline", category: "Sports & Athletics" },
  { word: "Archery", category: "Sports & Athletics" },
  { word: "Fencing", category: "Sports & Athletics" },
  { word: "Judo", category: "Sports & Athletics" },
  { word: "Taekwondo", category: "Sports & Athletics" },
  { word: "Karate", category: "Sports & Athletics" },
  { word: "KungFu", category: "Sports & Athletics" },
  { word: "Kickboxing", category: "Sports & Athletics" },
  { word: "MuayThai", category: "Sports & Athletics" },
  { word: "Wrestling", category: "Sports & Athletics" },
  { word: "Sumo", category: "Sports & Athletics" },
  { word: "Triathlon", category: "Sports & Athletics" },
  { word: "Decathlon", category: "Sports & Athletics" },
  { word: "HighJump", category: "Sports & Athletics" },
  { word: "Monopoly", category: "Games, Puzzles & Hobbies" },
  { word: "Scrabble", category: "Games, Puzzles & Hobbies" },
  { word: "Catan", category: "Games, Puzzles & Hobbies" },
  { word: "TicketToRide", category: "Games, Puzzles & Hobbies" },
  { word: "Risk", category: "Games, Puzzles & Hobbies" },
  { word: "Clue", category: "Games, Puzzles & Hobbies" },
  { word: "Battleship", category: "Games, Puzzles & Hobbies" },
  { word: "Twister", category: "Games, Puzzles & Hobbies" },
  { word: "Jenga", category: "Games, Puzzles & Hobbies" },
  { word: "ConnectFour", category: "Games, Puzzles & Hobbies" },
  { word: "Uno", category: "Games, Puzzles & Hobbies" },
  { word: "Poker", category: "Games, Puzzles & Hobbies" },
  { word: "Blackjack", category: "Games, Puzzles & Hobbies" },
  { word: "Roulette", category: "Games, Puzzles & Hobbies" },
  { word: "SlotMachine", category: "Games, Puzzles & Hobbies" },
  { word: "Craps", category: "Games, Puzzles & Hobbies" },
  { word: "Baccarat", category: "Games, Puzzles & Hobbies" },
  { word: "Mahjong", category: "Games, Puzzles & Hobbies" },
  { word: "Dominos", category: "Games, Puzzles & Hobbies" },
  { word: "Backgammon", category: "Games, Puzzles & Hobbies" },
  { word: "Checkers", category: "Games, Puzzles & Hobbies" },
  { word: "Darts", category: "Games, Puzzles & Hobbies" },
  { word: "Billiards", category: "Games, Puzzles & Hobbies" },
  { word: "Foosball", category: "Games, Puzzles & Hobbies" },
  { word: "AirHockey", category: "Games, Puzzles & Hobbies" },
  { word: "Pinball", category: "Games, Puzzles & Hobbies" },
  { word: "RubiksCube", category: "Games, Puzzles & Hobbies" },
  { word: "JigsawPuzzle", category: "Games, Puzzles & Hobbies" },
  { word: "Crossword", category: "Games, Puzzles & Hobbies" },
  { word: "Sudoku", category: "Games, Puzzles & Hobbies" },
  { word: "Trivia", category: "Games, Puzzles & Hobbies" },
  { word: "Charades", category: "Games, Puzzles & Hobbies" },
  { word: "Pictionary", category: "Games, Puzzles & Hobbies" },
  { word: "TajMahal", category: "Travel & World Wonders" },
  { word: "EiffelTower", category: "Travel & World Wonders" },
  { word: "Colosseum", category: "Travel & World Wonders" },
  { word: "GreatWall", category: "Travel & World Wonders" },
  { word: "MachuPicchu", category: "Travel & World Wonders" },
  { word: "Petra", category: "Travel & World Wonders" },
  { word: "ChristRedeemer", category: "Travel & World Wonders" },
  { word: "BigBen", category: "Travel & World Wonders" },
  { word: "StatueOfLiberty", category: "Travel & World Wonders" },
  { word: "GoldenGate", category: "Travel & World Wonders" },
  { word: "BurjKhalifa", category: "Travel & World Wonders" },
  { word: "SydneyOpera", category: "Travel & World Wonders" },
  { word: "MountEverest", category: "Travel & World Wonders" },
  { word: "MountFuji", category: "Travel & World Wonders" },
  { word: "GrandCanyon", category: "Travel & World Wonders" },
  { word: "NiagaraFalls", category: "Travel & World Wonders" },
  { word: "VictoriaFalls", category: "Travel & World Wonders" },
  { word: "AmazonRiver", category: "Travel & World Wonders" },
  { word: "NileRiver", category: "Travel & World Wonders" },
  { word: "SaharaDesert", category: "Travel & World Wonders" },
  { word: "Antarctica", category: "Travel & World Wonders" },
  { word: "BermudaTriangle", category: "Travel & World Wonders" },
  { word: "Stonehenge", category: "Travel & World Wonders" },
  { word: "Louvre", category: "Travel & World Wonders" },
  { word: "Disneyland", category: "Travel & World Wonders" },
  { word: "UniversalStudios", category: "Travel & World Wonders" },
  { word: "TimesSquare", category: "Travel & World Wonders" },
  { word: "LasVegas", category: "Travel & World Wonders" },
  { word: "Hollywood", category: "Travel & World Wonders" },
  { word: "Venice", category: "Travel & World Wonders" },
  { word: "Santorini", category: "Travel & World Wonders" },
  { word: "Maldives", category: "Travel & World Wonders" },
  { word: "BoraBora", category: "Travel & World Wonders" },
  { word: "Hawaii", category: "Travel & World Wonders" },
  { word: "Bali", category: "Travel & World Wonders" },
  { word: "Phuket", category: "Travel & World Wonders" },
  { word: "Dubai", category: "Travel & World Wonders" },
  { word: "Paris", category: "Travel & World Wonders" },
  { word: "Tokyo", category: "Travel & World Wonders" },
  { word: "London", category: "Travel & World Wonders" },
  { word: "HighHeels", category: "Fashion & Luxury Brands" },
  { word: "Stilettos", category: "Fashion & Luxury Brands" },
  { word: "Loafers", category: "Fashion & Luxury Brands" },
  { word: "Boots", category: "Fashion & Luxury Brands" },
  { word: "Sandals", category: "Fashion & Luxury Brands" },
  { word: "FlipFlops", category: "Fashion & Luxury Brands" },
  { word: "Tuxedo", category: "Fashion & Luxury Brands" },
  { word: "Blazer", category: "Fashion & Luxury Brands" },
  { word: "Suit", category: "Fashion & Luxury Brands" },
  { word: "TrenchCoat", category: "Fashion & Luxury Brands" },
  { word: "LeatherJacket", category: "Fashion & Luxury Brands" },
  { word: "Cardigan", category: "Fashion & Luxury Brands" },
  { word: "Sweater", category: "Fashion & Luxury Brands" },
  { word: "Sari", category: "Fashion & Luxury Brands" },
  { word: "Lehenga", category: "Fashion & Luxury Brands" },
  { word: "Sherwani", category: "Fashion & Luxury Brands" },
  { word: "Turban", category: "Fashion & Luxury Brands" },
  { word: "Bowtie", category: "Fashion & Luxury Brands" },
  { word: "Necktie", category: "Fashion & Luxury Brands" },
  { word: "Suspenders", category: "Fashion & Luxury Brands" },
  { word: "Fedora", category: "Fashion & Luxury Brands" },
  { word: "Sombrero", category: "Fashion & Luxury Brands" },
  { word: "Beret", category: "Fashion & Luxury Brands" },
  { word: "Beanie", category: "Fashion & Luxury Brands" },
  { word: "Bandana", category: "Fashion & Luxury Brands" },
  { word: "Scarf", category: "Fashion & Luxury Brands" },
  { word: "Gloves", category: "Fashion & Luxury Brands" },
  { word: "Mittens", category: "Fashion & Luxury Brands" },
  { word: "Clutch", category: "Fashion & Luxury Brands" },
  { word: "Wallet", category: "Fashion & Luxury Brands" },
  { word: "Rolex", category: "Fashion & Luxury Brands" },
  { word: "Cartier", category: "Fashion & Luxury Brands" },
  { word: "Gucci", category: "Fashion & Luxury Brands" },
  { word: "Prada", category: "Fashion & Luxury Brands" },
  { word: "Chanel", category: "Fashion & Luxury Brands" },
  { word: "Versace", category: "Fashion & Luxury Brands" },
  { word: "Armani", category: "Fashion & Luxury Brands" },
  { word: "Dior", category: "Fashion & Luxury Brands" },
  { word: "Balenciaga", category: "Fashion & Luxury Brands" },
  { word: "LouisVuitton", category: "Fashion & Luxury Brands" },
  { word: "Tiffany", category: "Fashion & Luxury Brands" },
  { word: "Spreadsheet", category: "Office & Career Life" },
  { word: "PowerPoint", category: "Office & Career Life" },
  { word: "MeetingRoom", category: "Office & Career Life" },
  { word: "Whiteboard", category: "Office & Career Life" },
  { word: "Stapler", category: "Office & Career Life" },
  { word: "Paperclip", category: "Office & Career Life" },
  { word: "Printer", category: "Office & Career Life" },
  { word: "Scanner", category: "Office & Career Life" },
  { word: "Photocopier", category: "Office & Career Life" },
  { word: "WaterCooler", category: "Office & Career Life" },
  { word: "CoffeeMachine", category: "Office & Career Life" },
  { word: "Cubicle", category: "Office & Career Life" },
  { word: "ErgonomicChair", category: "Office & Career Life" },
  { word: "DeskLamp", category: "Office & Career Life" },
  { word: "Briefcase", category: "Office & Career Life" },
  { word: "StickyNotes", category: "Office & Career Life" },
  { word: "Highlighter", category: "Office & Career Life" },
  { word: "Badge", category: "Office & Career Life" },
  { word: "Lanyard", category: "Office & Career Life" },
  { word: "Elevator", category: "Office & Career Life" },
  { word: "Reception", category: "Office & Career Life" },
  { word: "Conference", category: "Office & Career Life" },
  { word: "Appraisal", category: "Office & Career Life" },
  { word: "Increment", category: "Office & Career Life" },
  { word: "SickLeave", category: "Office & Career Life" },
  { word: "CasualLeave", category: "Office & Career Life" },
  { word: "WorkFromHome", category: "Office & Career Life" },
  { word: "Freelancer", category: "Office & Career Life" },
  { word: "Intern", category: "Office & Career Life" },
  { word: "Manager", category: "Office & Career Life" },
  { word: "CEO", category: "Office & Career Life" },
  { word: "Founder", category: "Office & Career Life" },
  { word: "Investor", category: "Office & Career Life" },
  { word: "Startup", category: "Office & Career Life" },
  { word: "PitchDeck", category: "Office & Career Life" },
  { word: "Synergy", category: "Office & Career Life" },
  { word: "AirConditioner", category: "Home & Living" },
  { word: "CeilingFan", category: "Home & Living" },
  { word: "Heater", category: "Home & Living" },
  { word: "Thermostat", category: "Home & Living" },
  { word: "Dishwasher", category: "Home & Living" },
  { word: "Toaster", category: "Home & Living" },
  { word: "AirFryer", category: "Home & Living" },
  { word: "Oven", category: "Home & Living" },
  { word: "Stove", category: "Home & Living" },
  { word: "Chimney", category: "Home & Living" },
  { word: "WaterPurifier", category: "Home & Living" },
  { word: "Juicer", category: "Home & Living" },
  { word: "Mixer", category: "Home & Living" },
  { word: "Grinder", category: "Home & Living" },
  { word: "Kettle", category: "Home & Living" },
  { word: "RiceCooker", category: "Home & Living" },
  { word: "PressureCooker", category: "Home & Living" },
  { word: "FryingPan", category: "Home & Living" },
  { word: "Saucepan", category: "Home & Living" },
  { word: "CuttingBoard", category: "Home & Living" },
  { word: "ChefKnife", category: "Home & Living" },
  { word: "Spatula", category: "Home & Living" },
  { word: "Whisk", category: "Home & Living" },
  { word: "Colander", category: "Home & Living" },
  { word: "Teapot", category: "Home & Living" },
  { word: "CoffeeMaker", category: "Home & Living" },
  { word: "DiningChair", category: "Home & Living" },
  { word: "Recliner", category: "Home & Living" },
  { word: "BeanBag", category: "Home & Living" },
  { word: "Bookshelf", category: "Home & Living" },
  { word: "Chandelier", category: "Home & Living" },
  { word: "Curtains", category: "Home & Living" },
  { word: "Rug", category: "Home & Living" },
  { word: "Carpet", category: "Home & Living" },
  { word: "Fireplace", category: "Home & Living" },
  { word: "Mattress", category: "Home & Living" },
  { word: "Duvet", category: "Home & Living" },
  { word: "DressingTable", category: "Home & Living" },
  { word: "Supernova", category: "Space & Astronomy" },
  { word: "BlackHole", category: "Space & Astronomy" },
  { word: "Wormhole", category: "Space & Astronomy" },
  { word: "Quasar", category: "Space & Astronomy" },
  { word: "Pulsar", category: "Space & Astronomy" },
  { word: "Nebula", category: "Space & Astronomy" },
  { word: "MilkyWay", category: "Space & Astronomy" },
  { word: "Andromeda", category: "Space & Astronomy" },
  { word: "SolarSystem", category: "Space & Astronomy" },
  { word: "Sun", category: "Space & Astronomy" },
  { word: "Mercury", category: "Space & Astronomy" },
  { word: "Venus", category: "Space & Astronomy" },
  { word: "Earth", category: "Space & Astronomy" },
  { word: "Mars", category: "Space & Astronomy" },
  { word: "Jupiter", category: "Space & Astronomy" },
  { word: "Saturn", category: "Space & Astronomy" },
  { word: "Uranus", category: "Space & Astronomy" },
  { word: "Neptune", category: "Space & Astronomy" },
  { word: "Pluto", category: "Space & Astronomy" },
  { word: "AsteroidBelt", category: "Space & Astronomy" },
  { word: "KuiperBelt", category: "Space & Astronomy" },
  { word: "OortCloud", category: "Space & Astronomy" },
  { word: "CometHalley", category: "Space & Astronomy" },
  { word: "ShootingStar", category: "Space & Astronomy" },
  { word: "SpaceStation", category: "Space & Astronomy" },
  { word: "HubbleTelescope", category: "Space & Astronomy" },
  { word: "JamesWebb", category: "Space & Astronomy" },
  { word: "ApolloEleven", category: "Space & Astronomy" },
  { word: "SaturnFive", category: "Space & Astronomy" },
  { word: "FalconHeavy", category: "Space & Astronomy" },
  { word: "Starship", category: "Space & Astronomy" },
  { word: "SpaceWalk", category: "Space & Astronomy" },
  { word: "ZeroGravity", category: "Space & Astronomy" },
  { word: "Cosmonaut", category: "Space & Astronomy" },
  { word: "Taikonaut", category: "Space & Astronomy" },
  { word: "SpaceSuit", category: "Space & Astronomy" },
  { word: "AirLock", category: "Space & Astronomy" },
  { word: "HeatShield", category: "Space & Astronomy" },
  { word: "SolarFlare", category: "Space & Astronomy" },
  { word: "Constellation", category: "Space & Astronomy" },
  { word: "ElectricGuitar", category: "Music & Instruments" },
  { word: "BassGuitar", category: "Music & Instruments" },
  { word: "AcousticGuitar", category: "Music & Instruments" },
  { word: "GrandPiano", category: "Music & Instruments" },
  { word: "Keyboard", category: "Music & Instruments" },
  { word: "Synthesizer", category: "Music & Instruments" },
  { word: "DrumKit", category: "Music & Instruments" },
  { word: "Bongos", category: "Music & Instruments" },
  { word: "Congas", category: "Music & Instruments" },
  { word: "Cajon", category: "Music & Instruments" },
  { word: "Tambourine", category: "Music & Instruments" },
  { word: "Cymbals", category: "Music & Instruments" },
  { word: "Xylophone", category: "Music & Instruments" },
  { word: "Saxophone", category: "Music & Instruments" },
  { word: "Clarinet", category: "Music & Instruments" },
  { word: "Flute", category: "Music & Instruments" },
  { word: "Oboe", category: "Music & Instruments" },
  { word: "Bassoon", category: "Music & Instruments" },
  { word: "Trumpet", category: "Music & Instruments" },
  { word: "Trombone", category: "Music & Instruments" },
  { word: "Tuba", category: "Music & Instruments" },
  { word: "FrenchHorn", category: "Music & Instruments" },
  { word: "Violin", category: "Music & Instruments" },
  { word: "Viola", category: "Music & Instruments" },
  { word: "Cello", category: "Music & Instruments" },
  { word: "DoubleBass", category: "Music & Instruments" },
  { word: "Harp", category: "Music & Instruments" },
  { word: "Banjo", category: "Music & Instruments" },
  { word: "Ukulele", category: "Music & Instruments" },
  { word: "Mandolin", category: "Music & Instruments" },
  { word: "Harmonica", category: "Music & Instruments" },
  { word: "Accordion", category: "Music & Instruments" },
  { word: "Bagpipes", category: "Music & Instruments" },
  { word: "Sitar", category: "Music & Instruments" },
  { word: "Tabla", category: "Music & Instruments" },
  { word: "Sarod", category: "Music & Instruments" },
  { word: "MicrophoneStand", category: "Music & Instruments" },
  { word: "Amplifier", category: "Music & Instruments" },
  { word: "Turntable", category: "Music & Instruments" },
  { word: "Boombox", category: "Music & Instruments" },
  { word: "VinylRecord", category: "Music & Instruments" },
  { word: "MagnifyingGlass", category: "Mystery, Spy & Heist" },
  { word: "Fingerprint", category: "Mystery, Spy & Heist" },
  { word: "Footprint", category: "Mystery, Spy & Heist" },
  { word: "SecretAgent", category: "Mystery, Spy & Heist" },
  { word: "FedoraHat", category: "Mystery, Spy & Heist" },
  { word: "Disguise", category: "Mystery, Spy & Heist" },
  { word: "FakeIdentity", category: "Mystery, Spy & Heist" },
  { word: "Silencer", category: "Mystery, Spy & Heist" },
  { word: "NightVision", category: "Mystery, Spy & Heist" },
  { word: "LaserGrid", category: "Mystery, Spy & Heist" },
  { word: "VaultDoor", category: "Mystery, Spy & Heist" },
  { word: "CombinationLock", category: "Mystery, Spy & Heist" },
  { word: "SafeBox", category: "Mystery, Spy & Heist" },
  { word: "MasterKey", category: "Mystery, Spy & Heist" },
  { word: "Lockpick", category: "Mystery, Spy & Heist" },
  { word: "EscapePlan", category: "Mystery, Spy & Heist" },
  { word: "GetawayCar", category: "Mystery, Spy & Heist" },
  { word: "Undercover", category: "Mystery, Spy & Heist" },
  { word: "Wiretap", category: "Mystery, Spy & Heist" },
  { word: "BugDetector", category: "Mystery, Spy & Heist" },
  { word: "WalkieTalkie", category: "Mystery, Spy & Heist" },
  { word: "SmokeBomb", category: "Mystery, Spy & Heist" },
  { word: "GrapplingHook", category: "Mystery, Spy & Heist" },
  { word: "Hacker", category: "Mystery, Spy & Heist" },
  { word: "Cipher", category: "Mystery, Spy & Heist" },
  { word: "SecretCode", category: "Mystery, Spy & Heist" },
  { word: "InvisibleInk", category: "Mystery, Spy & Heist" },
  { word: "Cryptogram", category: "Mystery, Spy & Heist" },
  { word: "TreasureMap", category: "Mystery, Spy & Heist" },
  { word: "LostCity", category: "Mystery, Spy & Heist" },
  { word: "GoldenIdol", category: "Mystery, Spy & Heist" },
  { word: "AncientCurse", category: "Mystery, Spy & Heist" },
  { word: "HiddenTomb", category: "Mystery, Spy & Heist" },
  { word: "Invisibility", category: "Superpowers & Magic" },
  { word: "Teleportation", category: "Superpowers & Magic" },
  { word: "Telekinesis", category: "Superpowers & Magic" },
  { word: "SuperStrength", category: "Superpowers & Magic" },
  { word: "SuperSpeed", category: "Superpowers & Magic" },
  { word: "MindReading", category: "Superpowers & Magic" },
  { word: "TimeTravel", category: "Superpowers & Magic" },
  { word: "Shapeshifter", category: "Superpowers & Magic" },
  { word: "XRayVision", category: "Superpowers & Magic" },
  { word: "ForceField", category: "Superpowers & Magic" },
  { word: "HealingFactor", category: "Superpowers & Magic" },
  { word: "Flight", category: "Superpowers & Magic" },
  { word: "LaserEyes", category: "Superpowers & Magic" },
  { word: "Pyrokinesis", category: "Superpowers & Magic" },
  { word: "Cryokinesis", category: "Superpowers & Magic" },
  { word: "Electrokinesis", category: "Superpowers & Magic" },
  { word: "Clairvoyance", category: "Superpowers & Magic" },
  { word: "Immortality", category: "Superpowers & Magic" },
  { word: "Elasticity", category: "Superpowers & Magic" },
  { word: "Intangibility", category: "Superpowers & Magic" },
];

// Global ring buffer to prevent words from repeating across games
const globalRecentWords: string[] = [];
const MAX_GLOBAL_RECENT = 250; // Keep the last 250 chosen words in global anti-repeat memory

export function pickWord(roomUsedWords: Set<string>): WordEntry {
  const roomUsedLower = new Set(Array.from(roomUsedWords).map(w => w.toLowerCase()));
  const globalRecentLower = new Set(globalRecentWords.map(w => w.toLowerCase()));

  // 1. First priority: words neither used in this room NOR used recently in other games
  let candidates = WORD_BANK.filter(
    w => !roomUsedLower.has(w.word.toLowerCase()) && !globalRecentLower.has(w.word.toLowerCase())
  );

  // 2. Second priority: if fresh global words run low, pick any word not yet used in THIS room
  if (candidates.length === 0) {
    candidates = WORD_BANK.filter(
      w => !roomUsedLower.has(w.word.toLowerCase())
    );
  }

  // 3. Fallback: if the room has exhausted words, reset room pool
  if (candidates.length === 0) {
    roomUsedWords.clear();
    candidates = WORD_BANK.filter(w => !globalRecentLower.has(w.word.toLowerCase()));
    if (candidates.length === 0) {
      candidates = WORD_BANK;
    }
  }

  // Pick randomly from eligible candidates
  const randomIndex = Math.floor(Math.random() * candidates.length);
  const selected = candidates[randomIndex];

  // Record in room history
  roomUsedWords.add(selected.word);

  // Record in global recent history FIFO
  globalRecentWords.push(selected.word);
  if (globalRecentWords.length > MAX_GLOBAL_RECENT) {
    globalRecentWords.shift();
  }

  return selected;
}
