export interface WordEntry {
  word: string;
  category: string;
}

export const WORD_BANK: WordEntry[] = [
  // ── Food & Treats (46) ─────────────────────────────────────────────────────
  { word: "Pizza", category: "Food & Drinks" },
  { word: "Sushi", category: "Food & Drinks" },
  { word: "Pancake", category: "Food & Drinks" },
  { word: "Coffee", category: "Food & Drinks" },
  { word: "Chocolate", category: "Food & Drinks" },
  { word: "Burger", category: "Food & Drinks" },
  { word: "Popcorn", category: "Food & Drinks" },
  { word: "Spaghetti", category: "Food & Drinks" },
  { word: "Lemon", category: "Food & Drinks" },
  { word: "Pineapple", category: "Food & Drinks" },
  { word: "Donut", category: "Food & Drinks" },
  { word: "Taco", category: "Food & Drinks" },
  { word: "Waffle", category: "Food & Drinks" },
  { word: "Sandwich", category: "Food & Drinks" },
  { word: "Cookie", category: "Food & Drinks" },
  { word: "Pretzel", category: "Food & Drinks" },
  { word: "Cupcake", category: "Food & Drinks" },
  { word: "Lasagna", category: "Food & Drinks" },
  { word: "Dumpling", category: "Food & Drinks" },
  { word: "Avocado", category: "Food & Drinks" },
  { word: "Mango", category: "Food & Drinks" },
  { word: "Burrito", category: "Food & Drinks" },
  { word: "Croissant", category: "Food & Drinks" },
  { word: "Honey", category: "Food & Drinks" },
  { word: "Cheesecake", category: "Food & Drinks" },
  { word: "Brownie", category: "Food & Drinks" },
  { word: "Omelet", category: "Food & Drinks" },
  { word: "Caramel", category: "Food & Drinks" },
  { word: "Mustard", category: "Food & Drinks" },
  { word: "Coconut", category: "Food & Drinks" },
  { word: "Watermelon", category: "Food & Drinks" },
  { word: "Strawberry", category: "Food & Drinks" },
  { word: "Mushroom", category: "Food & Drinks" },
  { word: "Sausage", category: "Food & Drinks" },
  { word: "Bagel", category: "Food & Drinks" },
  { word: "Biscuit", category: "Food & Drinks" },
  { word: "Peanut", category: "Food & Drinks" },
  { word: "Butter", category: "Food & Drinks" },
  { word: "Bacon", category: "Food & Drinks" },
  { word: "Cherry", category: "Food & Drinks" },
  { word: "Peach", category: "Food & Drinks" },
  { word: "Garlic", category: "Food & Drinks" },
  { word: "Onion", category: "Food & Drinks" },
  { word: "Noodle", category: "Food & Drinks" },
  { word: "Barbecue", category: "Food & Drinks" },
  { word: "Marshmallow", category: "Food & Drinks" },

  // ── Animals & Wildlife (50) ────────────────────────────────────────────────
  { word: "Penguin", category: "Animals & Wildlife" },
  { word: "Elephant", category: "Animals & Wildlife" },
  { word: "Octopus", category: "Animals & Wildlife" },
  { word: "Kangaroo", category: "Animals & Wildlife" },
  { word: "Dolphin", category: "Animals & Wildlife" },
  { word: "Flamingo", category: "Animals & Wildlife" },
  { word: "Cheetah", category: "Animals & Wildlife" },
  { word: "Giraffe", category: "Animals & Wildlife" },
  { word: "Chameleon", category: "Animals & Wildlife" },
  { word: "Peacock", category: "Animals & Wildlife" },
  { word: "Hedgehog", category: "Animals & Wildlife" },
  { word: "Jellyfish", category: "Animals & Wildlife" },
  { word: "Gorilla", category: "Animals & Wildlife" },
  { word: "Koala", category: "Animals & Wildlife" },
  { word: "Panda", category: "Animals & Wildlife" },
  { word: "Zebra", category: "Animals & Wildlife" },
  { word: "Rhinoceros", category: "Animals & Wildlife" },
  { word: "Squirrel", category: "Animals & Wildlife" },
  { word: "Scorpion", category: "Animals & Wildlife" },
  { word: "Platypus", category: "Animals & Wildlife" },
  { word: "Hamster", category: "Animals & Wildlife" },
  { word: "Lobster", category: "Animals & Wildlife" },
  { word: "Mosquito", category: "Animals & Wildlife" },
  { word: "Leopard", category: "Animals & Wildlife" },
  { word: "Buffalo", category: "Animals & Wildlife" },
  { word: "Walrus", category: "Animals & Wildlife" },
  { word: "Seagull", category: "Animals & Wildlife" },
  { word: "Pelican", category: "Animals & Wildlife" },
  { word: "Panther", category: "Animals & Wildlife" },
  { word: "Hyena", category: "Animals & Wildlife" },
  { word: "Ostrich", category: "Animals & Wildlife" },
  { word: "Woodpecker", category: "Animals & Wildlife" },
  { word: "Vulture", category: "Animals & Wildlife" },
  { word: "Raccoon", category: "Animals & Wildlife" },
  { word: "Beaver", category: "Animals & Wildlife" },
  { word: "Badger", category: "Animals & Wildlife" },
  { word: "Chimpanzee", category: "Animals & Wildlife" },
  { word: "Sloth", category: "Animals & Wildlife" },
  { word: "Starfish", category: "Animals & Wildlife" },
  { word: "Seahorse", category: "Animals & Wildlife" },
  { word: "Turtle", category: "Animals & Wildlife" },
  { word: "Iguana", category: "Animals & Wildlife" },
  { word: "Crocodile", category: "Animals & Wildlife" },
  { word: "Parrot", category: "Animals & Wildlife" },
  { word: "Falcon", category: "Animals & Wildlife" },
  { word: "Owl", category: "Animals & Wildlife" },
  { word: "Otter", category: "Animals & Wildlife" },
  { word: "Antelope", category: "Animals & Wildlife" },
  { word: "Lemur", category: "Animals & Wildlife" },
  { word: "Salamander", category: "Animals & Wildlife" },

  // ── Objects & Inventions (50) ──────────────────────────────────────────────
  { word: "Guitar", category: "Objects & Inventions" },
  { word: "Telescope", category: "Objects & Inventions" },
  { word: "Umbrella", category: "Objects & Inventions" },
  { word: "Bicycle", category: "Objects & Inventions" },
  { word: "Camera", category: "Objects & Inventions" },
  { word: "Compass", category: "Objects & Inventions" },
  { word: "Parachute", category: "Objects & Inventions" },
  { word: "Microscope", category: "Objects & Inventions" },
  { word: "Hourglass", category: "Objects & Inventions" },
  { word: "Lantern", category: "Objects & Inventions" },
  { word: "Skateboard", category: "Objects & Inventions" },
  { word: "Hoverboard", category: "Objects & Inventions" },
  { word: "Backpack", category: "Objects & Inventions" },
  { word: "Flashlight", category: "Objects & Inventions" },
  { word: "Trumpet", category: "Objects & Inventions" },
  { word: "Violin", category: "Objects & Inventions" },
  { word: "Binoculars", category: "Objects & Inventions" },
  { word: "Scissors", category: "Objects & Inventions" },
  { word: "Helmet", category: "Objects & Inventions" },
  { word: "Magnet", category: "Objects & Inventions" },
  { word: "Drone", category: "Objects & Inventions" },
  { word: "Thermometer", category: "Objects & Inventions" },
  { word: "Battery", category: "Objects & Inventions" },
  { word: "Anchor", category: "Objects & Inventions" },
  { word: "Satellite", category: "Objects & Inventions" },
  { word: "Stethoscope", category: "Objects & Inventions" },
  { word: "Submarine", category: "Objects & Inventions" },
  { word: "Clock", category: "Objects & Inventions" },
  { word: "Mirror", category: "Objects & Inventions" },
  { word: "Calendar", category: "Objects & Inventions" },
  { word: "Blanket", category: "Objects & Inventions" },
  { word: "Pillow", category: "Objects & Inventions" },
  { word: "Hammock", category: "Objects & Inventions" },
  { word: "Ladder", category: "Objects & Inventions" },
  { word: "Candle", category: "Objects & Inventions" },
  { word: "Whistle", category: "Objects & Inventions" },
  { word: "Syringe", category: "Objects & Inventions" },
  { word: "Needle", category: "Objects & Inventions" },
  { word: "Padlock", category: "Objects & Inventions" },
  { word: "Shovel", category: "Objects & Inventions" },
  { word: "Screwdriver", category: "Objects & Inventions" },
  { word: "Wrench", category: "Objects & Inventions" },
  { word: "Hammer", category: "Objects & Inventions" },
  { word: "Microphone", category: "Objects & Inventions" },
  { word: "Headphones", category: "Objects & Inventions" },
  { word: "Speaker", category: "Objects & Inventions" },
  { word: "Calculator", category: "Objects & Inventions" },
  { word: "Suitcase", category: "Objects & Inventions" },
  { word: "Lighter", category: "Objects & Inventions" },
  { word: "Magnifier", category: "Objects & Inventions" },

  // ── Places & Landmarks (46) ────────────────────────────────────────────────
  { word: "Museum", category: "Places & Landmarks" },
  { word: "Library", category: "Places & Landmarks" },
  { word: "Airport", category: "Places & Landmarks" },
  { word: "Stadium", category: "Places & Landmarks" },
  { word: "Lighthouse", category: "Places & Landmarks" },
  { word: "Castle", category: "Places & Landmarks" },
  { word: "Pyramid", category: "Places & Landmarks" },
  { word: "Temple", category: "Places & Landmarks" },
  { word: "Canyon", category: "Places & Landmarks" },
  { word: "Waterfall", category: "Places & Landmarks" },
  { word: "Volcano", category: "Places & Landmarks" },
  { word: "Island", category: "Places & Landmarks" },
  { word: "Fortress", category: "Places & Landmarks" },
  { word: "Dungeon", category: "Places & Landmarks" },
  { word: "Observatory", category: "Places & Landmarks" },
  { word: "Skyscraper", category: "Places & Landmarks" },
  { word: "Aquarium", category: "Places & Landmarks" },
  { word: "Carnival", category: "Places & Landmarks" },
  { word: "Jungle", category: "Places & Landmarks" },
  { word: "Theater", category: "Places & Landmarks" },
  { word: "Planetarium", category: "Places & Landmarks" },
  { word: "Factory", category: "Places & Landmarks" },
  { word: "Harbor", category: "Places & Landmarks" },
  { word: "Casino", category: "Places & Landmarks" },
  { word: "Sanctuary", category: "Places & Landmarks" },
  { word: "Palace", category: "Places & Landmarks" },
  { word: "Monument", category: "Places & Landmarks" },
  { word: "Cave", category: "Places & Landmarks" },
  { word: "Glacier", category: "Places & Landmarks" },
  { word: "Desert", category: "Places & Landmarks" },
  { word: "Prison", category: "Places & Landmarks" },
  { word: "Hospital", category: "Places & Landmarks" },
  { word: "Cinema", category: "Places & Landmarks" },
  { word: "Runway", category: "Places & Landmarks" },
  { word: "Windmill", category: "Places & Landmarks" },
  { word: "Mine", category: "Places & Landmarks" },
  { word: "Bridge", category: "Places & Landmarks" },
  { word: "Igloo", category: "Places & Landmarks" },
  { word: "Citadel", category: "Places & Landmarks" },
  { word: "Oasis", category: "Places & Landmarks" },
  { word: "Valley", category: "Places & Landmarks" },
  { word: "Beach", category: "Places & Landmarks" },
  { word: "Station", category: "Places & Landmarks" },
  { word: "Laboratory", category: "Places & Landmarks" },
  { word: "Cemetery", category: "Places & Landmarks" },
  { word: "Cathedral", category: "Places & Landmarks" },

  // ── People & Roles (45) ────────────────────────────────────────────────────
  { word: "Astronaut", category: "People & Roles" },
  { word: "Detective", category: "People & Roles" },
  { word: "Magician", category: "People & Roles" },
  { word: "Firefighter", category: "People & Roles" },
  { word: "Pirate", category: "People & Roles" },
  { word: "Ninja", category: "People & Roles" },
  { word: "Chef", category: "People & Roles" },
  { word: "Surgeon", category: "People & Roles" },
  { word: "Clown", category: "People & Roles" },
  { word: "Superhero", category: "People & Roles" },
  { word: "Gladiator", category: "People & Roles" },
  { word: "Archeologist", category: "People & Roles" },
  { word: "Viking", category: "People & Roles" },
  { word: "Pilot", category: "People & Roles" },
  { word: "Sculptor", category: "People & Roles" },
  { word: "Blacksmith", category: "People & Roles" },
  { word: "Knight", category: "People & Roles" },
  { word: "Samurai", category: "People & Roles" },
  { word: "Pharaoh", category: "People & Roles" },
  { word: "Spy", category: "People & Roles" },
  { word: "Lifeguard", category: "People & Roles" },
  { word: "Captain", category: "People & Roles" },
  { word: "Judge", category: "People & Roles" },
  { word: "Wizard", category: "People & Roles" },
  { word: "Carpenter", category: "People & Roles" },
  { word: "Plumber", category: "People & Roles" },
  { word: "Soldier", category: "People & Roles" },
  { word: "Sailor", category: "People & Roles" },
  { word: "Diver", category: "People & Roles" },
  { word: "Barber", category: "People & Roles" },
  { word: "Waiter", category: "People & Roles" },
  { word: "Baker", category: "People & Roles" },
  { word: "Electrician", category: "People & Roles" },
  { word: "Painter", category: "People & Roles" },
  { word: "Miner", category: "People & Roles" },
  { word: "Postman", category: "People & Roles" },
  { word: "Guard", category: "People & Roles" },
  { word: "Queen", category: "People & Roles" },
  { word: "Prince", category: "People & Roles" },
  { word: "Cowboy", category: "People & Roles" },
  { word: "Emperor", category: "People & Roles" },
  { word: "Hunter", category: "People & Roles" },
  { word: "Ghost", category: "People & Roles" },
  { word: "Monster", category: "People & Roles" },
  { word: "Genie", category: "People & Roles" },

  // ── Nature & Weather (45) ──────────────────────────────────────────────────
  { word: "Tornado", category: "Nature & Weather" },
  { word: "Cactus", category: "Nature & Weather" },
  { word: "Avalanche", category: "Nature & Weather" },
  { word: "Rainforest", category: "Nature & Weather" },
  { word: "Coral", category: "Nature & Weather" },
  { word: "Blizzard", category: "Nature & Weather" },
  { word: "Lightning", category: "Nature & Weather" },
  { word: "Earthquake", category: "Nature & Weather" },
  { word: "Asteroid", category: "Nature & Weather" },
  { word: "Galaxy", category: "Nature & Weather" },
  { word: "Planet", category: "Nature & Weather" },
  { word: "Moon", category: "Nature & Weather" },
  { word: "Comet", category: "Nature & Weather" },
  { word: "Meteor", category: "Nature & Weather" },
  { word: "Rainbow", category: "Nature & Weather" },
  { word: "Thunder", category: "Nature & Weather" },
  { word: "Cloud", category: "Nature & Weather" },
  { word: "River", category: "Nature & Weather" },
  { word: "Geyser", category: "Nature & Weather" },
  { word: "Tsunami", category: "Nature & Weather" },
  { word: "Mirage", category: "Nature & Weather" },
  { word: "Nebula", category: "Nature & Weather" },
  { word: "Crater", category: "Nature & Weather" },
  { word: "Horizon", category: "Nature & Weather" },
  { word: "Sunrise", category: "Nature & Weather" },
  { word: "Sunset", category: "Nature & Weather" },
  { word: "Wave", category: "Nature & Weather" },
  { word: "Forest", category: "Nature & Weather" },
  { word: "Mountain", category: "Nature & Weather" },
  { word: "Meadow", category: "Nature & Weather" },
  { word: "Swamp", category: "Nature & Weather" },
  { word: "Lagoon", category: "Nature & Weather" },
  { word: "Breeze", category: "Nature & Weather" },
  { word: "Frost", category: "Nature & Weather" },
  { word: "Iceberg", category: "Nature & Weather" },
  { word: "Wildfire", category: "Nature & Weather" },
  { word: "Dewdrop", category: "Nature & Weather" },
  { word: "Starlight", category: "Nature & Weather" },
  { word: "Eclipse", category: "Nature & Weather" },
  { word: "Dusk", category: "Nature & Weather" },
  { word: "Aurora", category: "Nature & Weather" },
  { word: "Quicksand", category: "Nature & Weather" },
  { word: "Pebble", category: "Nature & Weather" },
  { word: "Fossil", category: "Nature & Weather" },
  { word: "Amber", category: "Nature & Weather" },

  // ── Sports & Activities (42) ───────────────────────────────────────────────
  { word: "Soccer", category: "Sports & Hobbies" },
  { word: "Bowling", category: "Sports & Hobbies" },
  { word: "Surfing", category: "Sports & Hobbies" },
  { word: "Archery", category: "Sports & Hobbies" },
  { word: "Boxing", category: "Sports & Hobbies" },
  { word: "Kayak", category: "Sports & Hobbies" },
  { word: "Skiing", category: "Sports & Hobbies" },
  { word: "Chess", category: "Sports & Hobbies" },
  { word: "Billiards", category: "Sports & Hobbies" },
  { word: "Marathon", category: "Sports & Hobbies" },
  { word: "Gymnastics", category: "Sports & Hobbies" },
  { word: "Cricket", category: "Sports & Hobbies" },
  { word: "Snowboard", category: "Sports & Hobbies" },
  { word: "Rodeo", category: "Sports & Hobbies" },
  { word: "Tennis", category: "Sports & Hobbies" },
  { word: "Badminton", category: "Sports & Hobbies" },
  { word: "Baseball", category: "Sports & Hobbies" },
  { word: "Hockey", category: "Sports & Hobbies" },
  { word: "Rugby", category: "Sports & Hobbies" },
  { word: "Volleyball", category: "Sports & Hobbies" },
  { word: "Wrestling", category: "Sports & Hobbies" },
  { word: "Fencing", category: "Sports & Hobbies" },
  { word: "Golf", category: "Sports & Hobbies" },
  { word: "Darts", category: "Sports & Hobbies" },
  { word: "Frisbee", category: "Sports & Hobbies" },
  { word: "Origami", category: "Sports & Hobbies" },
  { word: "Gardening", category: "Sports & Hobbies" },
  { word: "Knitting", category: "Sports & Hobbies" },
  { word: "Fishing", category: "Sports & Hobbies" },
  { word: "Juggling", category: "Sports & Hobbies" },
  { word: "Pottery", category: "Sports & Hobbies" },
  { word: "Painting", category: "Sports & Hobbies" },
  { word: "Hiking", category: "Sports & Hobbies" },
  { word: "Camping", category: "Sports & Hobbies" },
  { word: "Scuba", category: "Sports & Hobbies" },
  { word: "Rafting", category: "Sports & Hobbies" },
  { word: "Acrobatics", category: "Sports & Hobbies" },
  { word: "Snorkeling", category: "Sports & Hobbies" },
  { word: "Rowing", category: "Sports & Hobbies" },
  { word: "Karate", category: "Sports & Hobbies" },
  { word: "Ballet", category: "Sports & Hobbies" },
  { word: "Polo", category: "Sports & Hobbies" },

  // ── Fantasy, Sci-Fi & Adventure (46) ───────────────────────────────────────
  { word: "Spaceship", category: "Fantasy & Sci-Fi" },
  { word: "Alien", category: "Fantasy & Sci-Fi" },
  { word: "Dragon", category: "Fantasy & Sci-Fi" },
  { word: "Robot", category: "Fantasy & Sci-Fi" },
  { word: "Portal", category: "Fantasy & Sci-Fi" },
  { word: "Cyborg", category: "Fantasy & Sci-Fi" },
  { word: "Timepiece", category: "Fantasy & Sci-Fi" },
  { word: "Hologram", category: "Fantasy & Sci-Fi" },
  { word: "Laser", category: "Fantasy & Sci-Fi" },
  { word: "Crystal", category: "Fantasy & Sci-Fi" },
  { word: "Wand", category: "Fantasy & Sci-Fi" },
  { word: "Phoenix", category: "Fantasy & Sci-Fi" },
  { word: "Mummy", category: "Fantasy & Sci-Fi" },
  { word: "Vampire", category: "Fantasy & Sci-Fi" },
  { word: "Werewolf", category: "Fantasy & Sci-Fi" },
  { word: "Zombie", category: "Fantasy & Sci-Fi" },
  { word: "Griffin", category: "Fantasy & Sci-Fi" },
  { word: "Mermaid", category: "Fantasy & Sci-Fi" },
  { word: "Goblin", category: "Fantasy & Sci-Fi" },
  { word: "Giant", category: "Fantasy & Sci-Fi" },
  { word: "Sorcerer", category: "Fantasy & Sci-Fi" },
  { word: "Potion", category: "Fantasy & Sci-Fi" },
  { word: "Teleport", category: "Fantasy & Sci-Fi" },
  { word: "Android", category: "Fantasy & Sci-Fi" },
  { word: "Treasure", category: "Fantasy & Sci-Fi" },
  { word: "Relic", category: "Fantasy & Sci-Fi" },
  { word: "Armor", category: "Fantasy & Sci-Fi" },
  { word: "Shield", category: "Fantasy & Sci-Fi" },
  { word: "Sword", category: "Fantasy & Sci-Fi" },
  { word: "Catapult", category: "Fantasy & Sci-Fi" },
  { word: "Chariot", category: "Fantasy & Sci-Fi" },
  { word: "Cauldron", category: "Fantasy & Sci-Fi" },
  { word: "Spellbook", category: "Fantasy & Sci-Fi" },
  { word: "Spacesuit", category: "Fantasy & Sci-Fi" },
  { word: "Rocket", category: "Fantasy & Sci-Fi" },
  { word: "Hovercraft", category: "Fantasy & Sci-Fi" },
  { word: "Blaster", category: "Fantasy & Sci-Fi" },
  { word: "Mutant", category: "Fantasy & Sci-Fi" },
  { word: "Gargoyle", category: "Fantasy & Sci-Fi" },
  { word: "Siren", category: "Fantasy & Sci-Fi" },
  { word: "Minotaur", category: "Fantasy & Sci-Fi" },
  { word: "Kraken", category: "Fantasy & Sci-Fi" },
  { word: "Pegasus", category: "Fantasy & Sci-Fi" },
  { word: "Amulet", category: "Fantasy & Sci-Fi" },
  { word: "Scepter", category: "Fantasy & Sci-Fi" },
  { word: "Crown", category: "Fantasy & Sci-Fi" }
];

// Global ring buffer to prevent words from repeating across different rooms and games
const globalRecentWords: string[] = [];
const MAX_GLOBAL_RECENT = 200; // Keep the last 200 chosen words in global anti-repeat memory

export function pickWord(roomUsedWords: Set<string>): WordEntry {
  const roomUsedLower = new Set(Array.from(roomUsedWords).map(w => w.toLowerCase()));
  const globalRecentLower = new Set(globalRecentWords.map(w => w.toLowerCase()));

  // 1. Highest priority: words neither used in this room NOR used recently in other games
  let candidates = WORD_BANK.filter(
    w => !roomUsedLower.has(w.word.toLowerCase()) && !globalRecentLower.has(w.word.toLowerCase())
  );

  // 2. Second priority: if fresh global words run low, pick any word not yet used in THIS room
  if (candidates.length === 0) {
    candidates = WORD_BANK.filter(
      w => !roomUsedLower.has(w.word.toLowerCase())
    );
  }

  // 3. Fallback: if the room has exhausted almost all 370+ words, reset room pool
  if (candidates.length === 0) {
    roomUsedWords.clear();
    candidates = WORD_BANK.filter(w => !globalRecentLower.has(w.word.toLowerCase()));
    if (candidates.length === 0) {
      candidates = WORD_BANK;
    }
  }

  // Pick randomly from eligible candidates
  const randomIndex = Math.floor(Math.random() * candidates.length);
  const selected = candidates[randomIndex];

  // Record in room history
  roomUsedWords.add(selected.word);

  // Record in global recent history FIFO
  globalRecentWords.push(selected.word);
  if (globalRecentWords.length > MAX_GLOBAL_RECENT) {
    globalRecentWords.shift();
  }

  return selected;
}
